import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';import{marked}from'file:///C:/Users/sausau/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked/lib/marked.esm.js';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),src=path.join(here,'src'),dist=path.join(here,'dist');fs.mkdirSync(dist,{recursive:true});for(const f of['index.html','styles.css','app.js'])fs.copyFileSync(path.join(src,f),path.join(dist,f));const read=f=>fs.readFileSync(path.join(root,f),'utf8').replace(/^\uFEFF/,''),html=f=>marked.parse(read(f)),tasks=f=>[...read(f).matchAll(/^###?\s+(?:Aufgabe|Selbsttest|Abschluss|Block)\s*([^\r\n]*)/gmi)].map(m=>m[0].replace(/^#+\s*/,'').trim()).slice(0,6);
const specs=[{id:'tag-1',date:'26.09.2026',title:'Tag 1 · Nervensystem, Frühgeburt, N. medianus',focus:'Neuro · Pädiatrie · PNS',file:'study/packs/TAG_01_26-09.md',solution:'study/packs/TAG_01_LOESUNGEN.md',summary:'Grundbegriffe sicher unterscheiden, Reifezeichen erkennen und den N. medianus praktisch wiedergeben.'},{id:'tag-2',date:'27.09.2026',title:'Tag 2 · Rückenmark, Blase, N. radialis',focus:'Anatomie 3 · Gyn · PNS',file:'study/packs/TAG_02_27-09.md',solution:'study/packs/TAG_02_LOESUNGEN.md',summary:'Spinalkanal und Rückenmark erklären, Blasenfunktion ordnen und den N. radialis prüfen.'},{id:'tag-3',date:'28.09.2026',title:'Tag 3 · Reflexe, Asphyxie, mündliche Neuro',focus:'Neuro · Pädiatrie · mündlich',file:'study/packs/TAG_03_28-09.md',solution:'study/packs/TAG_03_LOESUNGEN.md',summary:'Reflexe und Kennmuskeln abrufen, Risiken beim Frühgeborenen verstehen und frei erklären.'}];
const stories={
'tag-1':[
{kind:'Kopfkino',title:'Die heiße Herdplatte',prompt:'Du berührst aus Versehen eine heiße Platte. Welche Information muss zuerst wohin – und welcher Befehl kommt zurück?',answer:'Die Temperatur- und Schmerzmeldung läuft <strong>afferent</strong> von den Rezeptoren zum ZNS. Der motorische Befehl läuft <strong>efferent</strong> vom ZNS zur Muskulatur. Merksatz: <em>Afferent arrives, efferent exits.</em> Zeige die beiden Richtungen mit zwei Pfeilen.'},
{kind:'Alltagsbild',title:'Ein Nerv ist wie ein mehrschichtiges Kabel',prompt:'Was schützt eine einzelne Faser, ein Faserbündel und schließlich den ganzen Nerv?',answer:'Wie bei einem Kabel liegt Schutz Schicht um Schicht: <strong>Endoneurium</strong> um die einzelne Nervenfaser, <strong>Perineurium</strong> um ein Faszikel, <strong>Epineurium</strong> um den gesamten Nerv. Zeichne drei Kreise ineinander und beschrifte sie von innen nach außen.'},
{kind:'Patientenfall',title:'Nachts kribbelt Daumen bis Mittelfinger',prompt:'Eine Patientin wacht nachts mit Kribbeln in Daumen, Zeige- und Mittelfinger auf. Welcher Nerv könnte eingeengt sein, und welche Daumenbewegung kann schwächer werden?',answer:'Das passt zum <strong>N. medianus</strong>, häufig im Karpaltunnel. Die Opposition des Daumens kann schwächer werden. Probiere die Opposition: Berühre mit der Daumenkuppe nacheinander die anderen Fingerkuppen.'}],
'tag-2':[
{kind:'Kopfkino',title:'Rückenmark im Schutzkanal',prompt:'Stell dir einen empfindlichen Datenstrang in einem knöchernen Tunnel vor. Was ist der Tunnel, was der Datenstrang?',answer:'Der knöcherne Tunnel ist der <strong>Canalis vertebralis</strong>, der Datenstrang das <strong>Rückenmark</strong>. Die Wirbel schützen; Rückenmark und Spinalnerven übertragen Informationen zwischen Körper und Gehirn.'},
{kind:'Alltagsbild',title:'Die Blase als Tank mit Sensor und Ventil',prompt:'Was muss passieren, damit sich die Blase füllt, ohne dass ständig Urin austritt?',answer:'Der Detrusor bleibt in der Speicherphase entspannt, die Verschlüsse halten. Dehnungsrezeptoren melden den Füllstand. Bei der Miktion kontrahiert der Detrusor und die Verschlüsse öffnen koordiniert. Danach die echten Begriffe laut in dieser Reihenfolge nennen.'},
{kind:'Patientenfall',title:'Die Hand hängt nach unten',prompt:'Nach langem Druck auf den Oberarm kann ein Patient das Handgelenk nicht mehr gut strecken. Welcher Nerv passt dazu?',answer:'Typisch ist eine Schädigung des <strong>N. radialis</strong>. Seine motorische Aufgabe wird sichtbar, wenn du das Handgelenk gegen Widerstand nach oben streckst. Das klinische Bild heißt Fallhand.'}],
'tag-3':[
{kind:'Kopfkino',title:'Der Reflex als sehr kurze Alarmleitung',prompt:'Warum zieht sich das Bein schon zurück, bevor du den Schmerz bewusst einordnest?',answer:'Der Reflexbogen wird auf Rückenmarksebene verschaltet. Rezeptor → afferente Faser → Rückenmark → efferente Faser → Muskel. Die bewusste Wahrnehmung im Gehirn folgt, aber die Schutzreaktion kann vorher starten.'},
{kind:'Patientenfall',title:'Sauerstoffmangel rund um die Geburt',prompt:'Warum kann ein Sauerstoffmangel gleichzeitig Gehirn, Herz und andere Organe gefährden?',answer:'Alle Organe brauchen Sauerstoff zur Energiegewinnung. Bei einer Asphyxie reicht die Versorgung nicht aus; besonders empfindliche Organe können geschädigt werden. Denke an eine Stadt, deren Stromversorgung ausfällt – kritische Einrichtungen fallen zuerst auf.'},
{kind:'Prüfungsszene',title:'Erklären statt aufsagen',prompt:'Du bekommst mündlich die Frage: „Was ist ein Reflexbogen?“ Wie würdest du in 30 Sekunden beginnen?',answer:'Starte mit der Funktion: „Ein Reflexbogen ermöglicht eine schnelle, unwillkürliche Reaktion auf einen Reiz.“ Nenne dann die fünf Stationen und schließe mit einem Beispiel, etwa dem Patellarsehnenreflex. So bekommt die Antwort Struktur statt einer losen Wortliste.'}]};
const packs=specs.map(p=>({...p,stories:stories[p.id],html:html(p.file),solutionHtml:html(p.solution),tasks:tasks(p.file).length?tasks(p.file):['Lernstoff aktiv wiedergeben','Selbsttest ohne Vorlage lösen','Fehler notieren']})),data={exams:[{date:'2026-10-08',label:'Prüfung 1',subjects:'Anatomie 1 · Anatomie 3 · Neurophysiologie'},{date:'2026-10-09',label:'Prüfung 2',subjects:'PT Orthopädie · Gynäkologie · Pädiatrie'},{date:'2026-10-13',label:'Prüfung 3 + 4',subjects:'Mündlich Neuro · PNS / Manuelle Therapie'}],packs,planDocs:[{title:'Anschaulich lernen',html:html('study/03_ANSCHAULICH_LERNEN.md')},{title:'So lernst du mit diesem Portal',html:html('study/00_SO_LERNST_DU.md')},{title:'Dein täglicher 3-Stunden-Plan',html:html('study/02_TAGESPLAN.md')}],mapDocs:[{title:'Gesamte Stoffkarte',html:html('study/01_STOFFLANDKARTE.md')}]};fs.writeFileSync(path.join(dist,'content.js'),`window.LEARNING_CONTENT = ${JSON.stringify(data)};\n`,'utf8');console.log(`Built ${packs.length} learning packs in ${dist}`);
