import {add} from './library-core.mjs';
add('anatomie','knochenpunkte','Knochenpunkte lesen wie eine Landkarte',1,'Lateinische Begriffe an Form, Lage und Funktion festmachen.',[['s16','1–8'],['s17','3–6'],['s18','1']],`
### Ein Name enthält oft schon eine Beschreibung
**Caput** = Kopf, **Collum** = Hals, **Corpus** = Körper. **Processus** bezeichnet einen Fortsatz, **Fossa** eine Grube, **Sulcus** eine Rinne, **Foramen** eine Öffnung. **Tuberculum** und **Tuberositas** sind Erhebungen, häufig als Ansatz-/Ursprungsbereiche wichtig. **Facies articularis** ist eine Gelenkfläche.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Lateinische Knochenpunkte funktionieren wie deutsche Straßennamen, die schon beschreiben, was dort ist: "Kirchgasse" liegt bei einer Kirche, "Brückenstraße" bei einer Brücke. Genauso beschreibt "Fossa" schon eine Grube, "Tuberositas" schon eine raue Erhebung – der Name selbst ist die halbe Beschreibung. Wer eine neue Adresse lernt, schaut trotzdem zuerst auf die Karte (Knochen, Seite, Lage) und liest den Namen erst danach als Bestätigung – genau in dieser Reihenfolge solltest du auch einen unbekannten Knochenpunkt angehen.</p></div>

Lerne deshalb nicht zuerst eine isolierte Wortliste. Bestimme Knochen und Seite, orientiere proximal/distal sowie ventral/dorsal und suche dann die Form. Verknüpfe den Punkt mit einem Gelenkpartner, einer Sehne oder einem vorbeiziehenden Nerv.

### Anker aus deinen Blättern
| Region | Orientierungspunkte |
|---|---|
| Scapula | Spina scapulae, Acromion, Processus coracoideus, Cavitas glenoidalis |
| Humerus | Caput, Tuberculum majus/minus, Epicondylus medialis/lateralis, Trochlea, Capitulum |
| Unterarm | Caput radii, Tuberositas radii, Olecranon, Incisura trochlearis |
| Wirbel | Corpus, Arcus, Processus spinosus/transversus, Foramen vertebrale |

### Ursprung und Ansatz verstehen
Ein Muskel verbindet zwei oder mehr knöcherne Bereiche. Sein Verlauf relativ zur Gelenkachse hilft, die Wirkung zu verstehen. Ursprung und Ansatz sind anatomische Bezeichnungen; bei fixiertem distalem Abschnitt kann sich auch der üblicherweise als Ursprung bezeichnete Bereich bewegen.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Ein Muskel ist wie ein Gummiband, das zwischen zwei Wandhaken gespannt ist. Normalerweise denkst du: ein Haken hält fest (Ursprung), der andere wird herangezogen (Ansatz). Klemmst du aber den sonst beweglichen Haken fest – zum Beispiel weil die Hand am Reck festhält – zieht sich stattdessen der sonst „feste“ Haken heran. Das Gummiband selbst hat sich nicht verändert, nur welches Ende sich bewegen kann.</p></div>

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Dieses Kapitel liefert kein Fakten-Set, sondern ein Lese-Werkzeug: Knochen und Seite bestimmen, Form/Lage benennen, dann eine funktionelle Verbindung zu Gelenk, Muskel oder Nerv herstellen. Jedes folgende Kapitel wendet genau dieses Werkzeug auf einen neuen Gelenkabschnitt an – die Knochenpunkte selbst sind die Ankerpunkte, an denen sich Gelenke, Bänder und Muskeln später festmachen lassen.`,
'Finde am Ellenbogen zuerst die mediale Seite und den Epicondylus medialis. Dahinter verläuft der N. ulnaris. Jetzt hängen lateinischer Punkt, räumliche Lage und ein bekannter Nerv zusammen – statt drei getrennte Vokabeln zu bleiben.',
[['Grundlage','Was bedeutet Foramen?','Eine Öffnung beziehungsweise ein Loch.'],['Transfer','Wie würdest du einen unbekannten Knochenpunkt lernen?','Knochen und Seite bestimmen, Form/Lage benennen, dann eine funktionelle Verbindung zu Muskel, Gelenk oder Nerv herstellen.']],
'Diese Auswahl erschließt die vorhandenen Schulter-, Arm- und Wirbelsäulenblätter. Ein vollständiger Atlas aller Knochenpunkte des Körpers ist in diesen Uploads nicht enthalten.',
'Dieses Kapitel eröffnet Anatomie 1 und legt das Werkzeug für alle folgenden Kapitel: Die hier gelernten Knochenpunkte sind die Ankerpunkte, an denen die nächsten Kapitel Gelenke, Bänder und Muskeln festmachen.');
add('anatomie','schulterguertel','Schultergürtel: Das Schulterblatt bewegt mit',1,'Schultergelenk und Schultergürtel nicht verwechseln.',[['s18','1–2']],`
### Knochen und Verbindungen
Scapula und Clavicula bilden den Schultergürtel. Die Clavicula verbindet über das Sternoklavikulargelenk mit dem Sternum und über das Akromioklavikulargelenk mit der Scapula. Das scapulothorakale Gleitlager beschreibt das Gleiten des Schulterblatts am Brustkorb; es ist kein gewöhnliches knöchernes Synovialgelenk.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir ein Buch vor, das auf einem leicht gewölbten Tisch verschoben wird, statt in einem Scharnier zu klappen: Es gibt keine feste Achse, nur ein Gleiten der einen Fläche über die andere, mit Muskeln statt Gelenkschmiere dazwischen. Genauso "klappt" die Scapula nicht in einem echten Gelenk, sie gleitet nur am Brustkorb entlang. Deshalb zählt das scapulothorakale Gleitlager zwar zu den funktionellen Bewegungseinheiten des Schultergürtels, aber nicht zu den knöchernen Synovialgelenken wie Sterno- oder Akromioklavikulargelenk.</p></div>

### Bewegungen beobachten
**Elevation/Depression:** Schulterblatt nach oben/unten. **Protraktion/Retraktion:** um den Brustkorb nach vorne beziehungsweise zur Wirbelsäule zurück. Bei der Armhebung verändert sich zusätzlich die Rotation der Scapula. Der Humerus bewegt sich also auf einer selbst beweglichen Basis.

### Muskeln aus deinem Blatt
Ventral stehen M. subclavius und M. pectoralis minor. Für die Scapulaführung sind außerdem M. trapezius mit drei Anteilen, M. levator scapulae, Mm. rhomboidei major/minor und M. serratus anterior aufgeführt. Ordne zunächst Bewegung und Lage zu; nicht alle diese Muskeln werden vom N. accessorius versorgt. Dieser wichtige Nerv ist besonders dem Trapezius zugeordnet.

### Bänder wiederfinden
Dein Blatt nennt sternoklavikuläre und interklavikuläre Bänder sowie am lateralen Ende das Lig. acromioclaviculare und die Anteile trapezoideum/conoid(e)um des Lig. coracoclaviculare. Sie verbinden unterschiedliche Knochenpunkte – deshalb erst die Knochenkarte aufbauen.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Scapula und Clavicula sind hier keine neuen Namen – sie waren schon Knochenpunkte-Träger aus Kapitel 1. Neu ist, dass diese Punkte jetzt zu Gelenken und Bewegungen zusammengesetzt werden: eine bewegliche Basis statt einzelner Landkarten-Orte. Genau diese bewegliche Basis braucht das nächste Kapitel, wenn der eigentliche Armknochen darauf aufsitzt.`,
'Schiebe eine Tür auf und führe die Hand weit nach vorne. Beobachte, wie sich die Scapula am Brustkorb mitbewegt. Halte anschließend den Arm locker und ziehe die Schulterblätter nach hinten: Das ist eine Schultergürtelbewegung, auch ohne große Ellenbogenbewegung.',
[['Grundlage','Welche zwei Knochen gehören zum Schultergürtel?','Scapula und Clavicula.'],['Transfer','Warum erklärt das Glenohumeralgelenk allein nicht die gesamte Armhebung?','Weil Schulterblatt und Clavicula ihre Stellung mitverändern.']],'',
'Die Landkarte aus dem letzten Kapitel wird hier zum ersten Mal gebraucht: Scapula und Clavicula sind schon bekannte Knochenpunkte-Träger. Jetzt lernst du ihre Gelenke und Bewegungen als bewegliche Basis, auf der im nächsten Kapitel der eigentliche Armknochen aufsitzt.');
add('anatomie','schultergelenk','Glenohumeralgelenk: Beweglichkeit & Sicherung',2,'Ein großer Kopf trifft auf eine vergleichsweise kleine Pfanne.',[['s16','1–3'],['s16','9']],`
### Die Gelenkpartner
Caput humeri und Cavitas glenoidalis bilden das Glenohumeralgelenk. Der Oberarmkopf ist konvex, die Pfanne konkav. Das **Labrum glenoidale** vertieft beziehungsweise ergänzt den Pfannenrand. Eine große Beweglichkeit erfordert gute passive und aktive Führung.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir einen Golfball auf einem flachen Suppenteller vor – nicht in einem tiefen Eierbecher. Der Ball (Caput humeri) hat auf dem Teller (Cavitas glenoidalis) kaum knöchernen Halt, dafür aber viel Bewegungsspielraum in alle Richtungen. Das Labrum glenoidale ist wie ein aufgesetzter Wulst am Tellerrand, der etwas mehr Tiefe schafft. Weil der Teller allein nicht reicht, braucht der Ball zusätzlich Halteschnüre (Kapsel und Bänder) und eine Hand, die ihn aktiv nachführt (Rotatorenmanschette) – sonst würde er beim kleinsten Anstoß herunterrollen.</p></div>

### Welche Strukturen sichern?
Kapsel und Bänder begrenzen Bewegung passiv. Deine Blätter nennen die Ligg. glenohumeralia sowie das Lig. coracohumerale. Der **Recessus axillaris** ist eine Kapselreserve im unteren Bereich. Die Rotatorenmanschette trägt aktiv zur Zentrierung des Humeruskopfes bei.

Die lange Bizepssehne verläuft im Bereich des Gelenks und anschließend im Sulcus intertubercularis. Sehnenscheiden und Schleimbeutel ermöglichen reibungsarmes Gleiten. Verwechsle einen Schleimbeutel nicht mit der Gelenkpfanne.

### Bewegungen ordnen
Flexion/Extension, Abduktion/Adduktion und Innen-/Außenrotation beschreiben die Humerusbewegung. Die Gesamtbewegung des Arms enthält zusätzlich Schultergürtelbewegung. Die Randnotiz „Bankart“ bezieht sich auf eine Labrumverletzung; daraus folgt nicht pauschal „keine Bizepsaktivität“.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Caput humeri und Cavitas glenoidalis sind ebenfalls schon aus Kapitel 1 bekannte Knochenpunkte – hier bekommen sie zum ersten Mal ihre gemeinsame Gelenkfunktion, aufsitzend auf der beweglichen Basis aus Kapitel 2. Neu dazu kommt eine Frage, die in den ersten beiden Kapiteln noch nicht nötig war: Reicht die passive Führung durch Kapsel und Labrum allein, oder braucht ein Gelenk zusätzlich aktive Führung? Genau diese Frage beantwortet das nächste Kapitel.`,
'Denke an einen Ball auf einer flachen Unterlage. Der knöcherne Kontakt allein bietet wenig Führung. Kapsel, Labrum und aktive Muskelführung ergänzen sich. Der Vergleich erklärt die Aufgabe – die echte Schulter ist selbstverständlich kein frei aufliegender Ball.',
[['Grundlage','Welche Struktur ergänzt den Pfannenrand?','Das Labrum glenoidale.'],['Knifflig','Sind Labrum und Rotatorenmanschette beide aktive Muskeln?','Nein. Das Labrum ist ein passiver faserknorpeliger Rand; die Manschette besteht aus Muskeln/Sehnen und trägt aktiv zur Führung bei.']],'',
'Der Schultergürtel aus dem letzten Kapitel ist die bewegliche Basis; jetzt kommt das eigentliche Armgelenk dazu, das auf dieser Basis sitzt. Caput humeri und Cavitas glenoidalis kennst du bereits als Knochenpunkte aus Kapitel 1 – hier bekommen sie ihre gemeinsame Gelenkfunktion.');
add('anatomie','manschette','Rotatorenmanschette & Deltoideus',2,'Vier Muskeln über Lage, Ansatz und Bewegung verbinden.',[['s16','9–12']],`
### Das räumliche Muster
Die Manschette heißt häufig **SITS**: Supraspinatus, Infraspinatus, Teres minor, Subscapularis. Drei ziehen zum Tuberculum majus; der vorne liegende Subscapularis zum Tuberculum minus.

<div class="nest" role="img" aria-label="Die Rotatorenmanschette (SITS) enthält vier gleichrangige Muskeln"><div class="nest-outer"><div class="nest-label">Rotatorenmanschette · SITS</div><div class="nest-items"><div class="nest-inner"><strong>Supraspinatus</strong></div><div class="nest-inner"><strong>Infraspinatus</strong></div><div class="nest-inner"><strong>Teres minor</strong></div><div class="nest-inner"><strong>Subscapularis</strong></div></div></div></div>

| Muskel | Ursprung → Ansatz | Wirkung / Innervation |
|---|---|---|
| Supraspinatus | Fossa supraspinata → Tuberculum majus | unterstützt Abduktion; N. suprascapularis |
| Infraspinatus | Fossa infraspinata → Tuberculum majus | Außenrotation; N. suprascapularis |
| Teres minor | lateraler Scapularand → Tuberculum majus | Außenrotation, unterstützt Adduktion; N. axillaris |
| Subscapularis | Fossa subscapularis → Tuberculum minus | Innenrotation; Nn. subscapulares |

Die Ansätze am Tuberculum majus liegen auf unterschiedlichen Facetten: supra oben, infra mittig, teres minor unten. Gemeinsame Aufgabe ist auch die Gelenkführung.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Die vier Manschettenmuskeln wirken wie vier Zeltschnüre, die von verschiedenen Seiten an einem Mast ziehen und ihn dadurch mittig im Zentrum halten, egal in welche Richtung er sich neigt. Supraspinatus zieht von oben, Infraspinatus und Teres minor von hinten, Subscapularis von vorne – zusammen zentrieren sie den Oberarmkopf in der Pfanne. Der Deltoideus darüber ist dagegen kein Zeltseil, sondern die kräftige Hand, die den ganzen Zeltmast anhebt: Er bewegt den Arm großflächig, kann das aber nur sicher tun, weil die vier Schnüre den Kopf währenddessen zentriert halten.</p></div>

### Der Deltoideus darüber
Er entspringt an lateraler Clavicula, Acromion und Spina scapulae und setzt an der Tuberositas deltoidea an. Der N. axillaris versorgt ihn. Der mittlere Anteil unterstützt besonders Abduktion; vordere/hintere Anteile tragen je nach Stellung unter anderem zu Flexion/Extension und Rotation bei.

### So prüfst du dein Verständnis
Zeige erst die Scapulagrube, dann den Weg zum Humerus. Erkläre anschließend die Rotationsrichtung. Erst zuletzt rufst du den Nerv ab.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Die passive Sicherung aus dem letzten Kapitel – Kapsel, Labrum – bekommt hier ihre aktive Ergänzung: vier Muskeln, die an denselben Tuberculum-Punkten aus Kapitel 1 angreifen. Damit ist die erste vollständige Gelenkführung fertig, knöchern, passiv und aktiv zusammen. Der nächste Schritt wandert bewusst weiter den Arm hinunter, zum nächsten Gelenkkomplex.`,
'Stell dich vor eine geschlossene Tür, Ellenbogen am Körper. Eine sanfte gedachte Außenrotation führt den Unterarm nach außen. Ordne dazu Infraspinatus und Teres minor. Für die Gegenrichtung liegt der Subscapularis vorne. Es geht hier um das Bewegungsbild, nicht um einen diagnostischen Krafttest.',
[['Grundlage','Welcher Manschettenmuskel setzt am Tuberculum minus an?','M. subscapularis.'],['Knifflig','Welcher Nerv versorgt Teres minor und Deltoideus?','N. axillaris.']],
'Die handschriftliche Innervationstabelle enthält Unstimmigkeiten. Besonders Subscapularis wird nicht vom N. axillaris versorgt; die Zuordnung ist hier korrigiert. Anatomischer Abgleich: https://pubmed.ncbi.nlm.nih.gov/18472282/ .',
'Im letzten Kapitel hast du gelernt, dass Kapsel und Labrum passiv sichern, aber aktive Führung brauchen. Genau diese aktive Führung liefern die vier Muskeln dieses Kapitels – sie greifen an denselben Tuberculum-Punkten an, die du schon aus Kapitel 1 kennst.');
add('anatomie','ellenbogen-hand','Ellenbogen, Unterarm & Handwurzel',2,'Beugen ist nicht Drehen: Teilgelenke und Knochen unterscheiden.',[['s16','5–8']],`
### Drei Teilgelenke am Ellenbogen
Art. humeroulnaris, Art. humeroradialis und Art. radioulnaris proximalis arbeiten zusammen. Trochlea humeri und Incisura trochlearis ulnae bilden eine zentrale Führung für Flexion/Extension. Das Caput radii hat Kontakt zum Capitulum humeri und kann sich im Ringbandbereich drehen.

### Pronation und Supination
Proximales und distales Radioulnargelenk ermöglichen die Unterarmdrehung. In Pronation kreuzt der Radius die Ulna; in Supination liegen beide annähernd parallel. Die Membrana interossea verbindet die Schäfte. Pronation ist daher nicht einfach eine Drehung im Handgelenk.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Radius und Ulna verhalten sich wie zwei Essstäbchen, die oben (proximales Radioulnargelenk) und unten (distales Radioulnargelenk) gelenkig zusammengehalten werden, sich dazwischen aber frei zueinander verdrehen können. Liegen beide Stäbchen parallel, ist das Supination. Dreht sich der Radius so, dass er sich vor die Ulna schiebt und sie kreuzt, ist das Pronation. Weil beide Drehpunkte oben UND unten am Unterarm liegen, nicht am Handgelenk, ist Pronation/Supination eine Unterarmbewegung – das Handgelenk macht dabei etwas ganz anderes: Palmarflexion/Dorsalextension und Radial-/Ulnarabduktion.</p></div>

### Handwurzel – zwei Reihen
Von radial nach ulnar:

* Proximal: **Os scaphoideum, lunatum, triquetrum, pisiforme**.
* Distal: **Os trapezium, trapezoideum, capitatum, hamatum**.

<div class="nest" role="img" aria-label="Die Handwurzel enthält zwei Reihen mit je vier Knochen"><div class="nest-outer"><div class="nest-label">Handwurzel · radial → ulnar</div><div class="nest-items"><div class="nest-inner"><strong>Proximale Reihe</strong><small>Scaphoideum, Lunatum, Triquetrum, Pisiforme</small></div><div class="nest-inner"><strong>Distale Reihe</strong><small>Trapezium, Trapezoideum, Capitatum, Hamatum</small></div></div></div></div>

Das Pisiforme liegt palmar auf dem Triquetrum. Distal folgen Metakarpalia und Phalangen. Der Daumen besitzt zwei Phalangen; die anderen Finger drei. Am Handgelenk ordnest du Palmarflexion/Dorsalextension sowie Radial-/Ulnarabduktion zu.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Die acht Handwurzelknochen liegen wie zwei Reihen Pflastersteine nebeneinander, von der Daumenseite (radial) zur Kleinfingerseite (ulnar) verlegt. Die erste Reihe direkt unter dem Unterarm: Scaphoideum, Lunatum, Triquetrum, Pisiforme – wobei das Pisiforme wie ein zusätzlicher kleiner Stein obendrauf liegt, nicht in der Reihe selbst. Die zweite Reihe darunter, Richtung Finger: Trapezium, Trapezoideum, Capitatum, Hamatum. Zwei Reihen, radial nach ulnar durchgezählt – das ist die räumliche Eselsbrücke, nicht eine zufällige Namensliste.</p></div>

### Knochenpunkte verbinden
Tuberositas radii → Bizepsansatz. Olecranon → Trizepsansatz. Hinter dem Epicondylus medialis → Ulnarisverlauf. Damit erhält jeder Punkt eine Aufgabe.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Wieder dieselbe Lesetechnik aus Kapitel 1, jetzt auf den nächsten Gelenkkomplex angewendet: Tuberositas radii und Olecranon waren schon Knochenpunkte, hier bekommen sie ihre Gelenkmechanik. Mit Schultergürtel, Schultergelenk und jetzt Ellenbogen/Hand sind alle Gelenke des Arms bekannt – genau das braucht das nächste Kapitel, das erstmals alle diese Gelenke gemeinsam über ihre Muskeln verbindet.`,
'Drehe die Handfläche nach oben, als würdest du Suppe tragen, und dann nach unten. Beobachte den Unterarm statt nur die Hand. Nun beuge den Ellenbogen: Das ist eine andere Bewegung mit anderer Gelenkmechanik.',
[['Grundlage','Wie heißen die vier Knochen der proximalen Handwurzelreihe?','Scaphoideum, lunatum, triquetrum, pisiforme.'],['Transfer','Warum ist Pronation keine reine Handgelenkbewegung?','Weil Radius und Ulna sich über die proximalen und distalen Radioulnargelenke gegeneinander bewegen.']],'',
'Nachdem Schultergürtel und Schultergelenk aufgebaut sind, wandert der Blick den Arm hinunter zum nächsten großen Gelenkkomplex: Ellenbogen, Unterarmdrehung und Handwurzel. Tuberositas radii und Olecranon kennst du bereits als Knochenpunkte aus Kapitel 1 – hier bekommen sie ihre Gelenkmechanik.');
add('anatomie','armmuskeln','Oberarmmuskeln & große Schulterbeweger',3,'Von einer Muskelzeile zur erklärbaren Bewegung kommen.',[['s16','4'],['s16','10–12']],`
### Beugen, strecken und supinieren
**Bizeps:** Caput longum vom Tuberculum supraglenoidale, Caput breve vom Processus coracoideus; Ansatz an der Tuberositas radii mit zusätzlicher Aponeurose. Wirkung: Ellenbogenflexion und Supination, Unterstützung an der Schulter. Innervation: N. musculocutaneus.

**Brachialis:** distaler vorderer Humerus zur Ulna; kräftiger Ellenbogenbeuger. **Coracobrachialis:** Processus coracoideus zum medialen Humerus; unterstützt Flexion/Adduktion der Schulter. Beide sind dem N. musculocutaneus zugeordnet (Brachialis kann zusätzlich einen radialen Anteil haben).

**Trizeps:** langer Kopf von der Scapula unterhalb der Pfanne, übrige Köpfe vom Humerus; gemeinsamer Ansatz am Olecranon. Hauptaufgabe Ellenbogenextension, Innervation N. radialis. Nur der lange Kopf überquert zusätzlich das Schultergelenk.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Bizeps und Trizeps arbeiten wie zwei Zügel an einem Pferd: Zieht der eine an (Bizeps kontrahiert, Ellenbogen beugt), muss der andere nachgeben (Trizeps entspannt sich) – und umgekehrt. Kein Zügel bewegt das Pferd allein in beide Richtungen. Deshalb reicht "der Bizeps beugt den Ellenbogen" nicht als vollständige Antwort: Die Gegenbewegung braucht immer den Gegenspieler, hier den Trizeps über den N. radialis.</p></div>

### Große Muskeln zur Schulter
**Pectoralis major:** von Clavicula, Sternum/Rippenbereich und weiterem unteren Anteil zur Crista tuberculi majoris; Adduktion und Innenrotation, anteils-/stellungsabhängig Flexion oder Rückführung. Nn. pectorales.

**Latissimus dorsi:** großer Rücken-/Faszienursprung zur Crista tuberculi minoris; Extension, Adduktion und Innenrotation. N. thoracodorsalis. **Teres major:** unterer Scapulabereich ebenfalls zur Crista tuberculi minoris; ähnliche Schulterwirkung, subscapuläre Innervation. Er gehört nicht zur Rotatorenmanschette.

### Eine vollständige Antwort bauen
Nenne Muskel, Ursprung, Ansatz, Innervation, Funktion. Vermeide, jede Funktion unabhängig von Gelenkstellung als unveränderlich darzustellen.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Dies ist das erste echte Synthese-Kapitel: Es setzt kein neues Gelenk mehr voraus, sondern verbindet alle bisher gelernten Gelenke aus Kapitel 2 bis 5 über die Muskeln, die sie bewegen. Das geht erst jetzt, weil vorher noch nicht alle Gelenke bekannt waren. Das letzte Kapitel dieses Fachs wechselt danach bewusst die Körperregion – aber mit derselben Lesetechnik aus Kapitel 1.`,
'Beim Heranziehen einer Tür arbeitest du an Schulter und Ellenbogen. Frage getrennt: Welcher Muskel führt den Oberarm zurück, welcher beugt den Ellenbogen? So vermeidest du, „Ziehen“ als Wirkung nur eines Muskels zu lernen.',
[['Grundlage','Woran setzt der Trizeps an?','Am Olecranon der Ulna.'],['Knifflig','Warum ist Teres major trotz seines Namens kein Manschettenmuskel?','Zur Rotatorenmanschette gehören Supraspinatus, Infraspinatus, Teres minor und Subscapularis; Teres major hat einen anderen Verlauf und gehört nicht dazu.']],'',
'Jetzt sind alle Gelenke des Arms bekannt: Schultergürtel, Schultergelenk und Ellenbogen/Unterarm. Dieses Kapitel verbindet sie erstmals über die Muskeln, die sie bewegen – vom Bizeps am Ellenbogen bis zu Pectoralis major und Latissimus dorsi an der Schulter. Es ist die Anwendung aller vorherigen Kapitel in einer vollständigen Muskelantwort.');
add('anatomie','wirbelsaeule','Wirbelsäule, Bandscheibe & Kopfgelenke',2,'Wirbel wiedererkennen und Schutz, Last und Bewegung zuordnen.',[['s15','1–3'],['s17','1–6'],['s19','1–2']],`
### Die Abschnitte
7 Hals-, 12 Brust- und 5 Lendenwirbel bilden die beweglichen Abschnitte. Dazu kommen Kreuzbein und Steißbein mit verschmolzenen Anteilen. Lordose und Kyphose beschreiben die Krümmungsrichtungen. Nicht jeder einzelne Wirbel sieht gleich aus.

### Der Grundbauplan
Corpus vertebrae trägt Last. Arcus vertebrae bildet zusammen mit dem Körper das Foramen vertebrale. Benachbarte Wirbelöffnungen bilden den Kanal; die Foramina intervertebralia liegen seitlich zwischen benachbarten Wirbeln. Processus spinosus und transversi sind Fortsätze, Gelenkfortsätze bilden Facettengelenke.

### Bandscheibe und Bänder
Der Discus intervertebralis besitzt außen den **Anulus fibrosus** und innen den **Nucleus pulposus**. Die Endplatten vermitteln den Kontakt zum Wirbelkörper. Ligg. longitudinale anterius/posterius verlaufen längs, Ligamenta flava verbinden benachbarte Wirbelbögen; inter- und supraspinale Bänder liegen zwischen beziehungsweise an den Dornfortsätzen.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Eine Bandscheibe ist aufgebaut wie ein widerstandsfähiger Gummireifen mit einem gelartigen Kern: Der Anulus fibrosus ist die feste, faserige Reifenwand, die den Druck ringsherum auffängt. Der Nucleus pulposus ist die gallertartige Füllung darin, die sich bei Belastung leicht verformt und den Druck gleichmäßig verteilt, statt ihn an einer Stelle zu konzentrieren. Die Endplatten oben und unten sind wie die Felgen, über die der Reifen Kontakt zum Wirbelkörper hat. Ein "Reifen", der nur außen fest, aber innen leer wäre, würde bei einseitiger Last knicken – genau deshalb braucht die Bandscheibe beide Anteile gemeinsam.</p></div>

### Oben gilt ein besonderer Bauplan
Atlas (C1) trägt den Schädel, Axis (C2) besitzt den Dens. Atlanto-okzipital ist die Verbindung zum Schädel, atlanto-axial die zwischen C1/C2. Zwischen diesen oberen Einheiten liegen keine gewöhnlichen Bandscheiben wie weiter kaudal. Kleine subokzipitale Muskeln wie Rectus capitis posterior major/minor und Obliquus capitis superior/inferior führen feine Kopfbewegungen; die tiefe Rückenmuskulatur setzt sich unter anderem mit Multifidi und weiteren kurzen Systemen fort.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Dieselbe Lesetechnik aus Kapitel 1 – Knochen und Seite bestimmen, Form/Lage benennen, funktionelle Verbindung herstellen – funktioniert auch auf einen komplett neuen Gegenstand: den Wirbel statt den Armknochen. Das zeigt, dass das Werkzeug aus Kapitel 1 nicht armspezifisch war, sondern für jede Knochenstruktur gilt.

### Der ganze Weg durch Anatomie 1 – im Rückblick
Sieben Kapitel, ein Werkzeug: Kapitel 1 gab dir die Lesetechnik für jeden Knochenpunkt. Kapitel 2 bis 5 haben damit, Schritt für Schritt den Arm hinunter, ein Gelenk nach dem anderen aufgebaut – Schultergürtel als bewegliche Basis, Schultergelenk als eigentliches Armgelenk, Manschette als aktive Ergänzung zur passiven Sicherung, Ellenbogen/Hand als nächster Gelenkkomplex. Kapitel 6 hat zum ersten Mal alle diese Gelenke über ihre Muskeln miteinander verbunden – das ging erst, als alle Gelenke bekannt waren. Dieses letzte Kapitel zeigt, dass dieselbe Lesetechnik aus Kapitel 1 auch auf eine ganz andere Körperregion passt. Am Ende sind das keine sieben Einzelthemen, sondern ein einziges Werkzeug: sechsmal auf den Arm angewendet, ein siebtes Mal auf die Wirbelsäule.`,
'Halte eine gedachte Perlenkette: Die Löcher bilden gemeinsam einen Kanal, aber die Verbindung zwischen zwei Perlen ist eine andere Struktur. So trennst du Wirbelkanal, Zwischenwirbelloch und Bewegungssegment räumlich.',
[['Grundlage','Wie heißen Außenring und Kern der Bandscheibe?','Anulus fibrosus und Nucleus pulposus.'],['Knifflig','Ist das Foramen intervertebrale dasselbe wie das Foramen vertebrale?','Nein. Das erste liegt seitlich zwischen benachbarten Wirbeln; das zweite innerhalb eines einzelnen Wirbels und trägt zum Wirbelkanal bei.']],
'Die gescannten Blätter enthalten teils leere Beschriftungsfelder. Die Bibliothek erklärt die erkennbaren Strukturen, behauptet aber keine vollständige Rekonstruktion jeder handschriftlichen Notiz.',
'Die letzten sechs Kapitel haben den Arm von der Schulter bis zur Hand aufgebaut. Dieses letzte Kapitel wechselt bewusst die Region: Wirbelsäule, Bandscheibe und die besonderen oberen Kopfgelenke sind ein eigener Bauplan, der ohne den Arm auskommt – aber dieselbe Lesetechnik aus Kapitel 1 nutzt, um jeden Wirbel als Landkarte zu verstehen.');

add('pns','nerven-schema','Ein Nerv, fünf Fragen',1,'Für alle sechs Nerven dasselbe räumliche Schema verwenden.',[['s03','6–8'],['s06','11–12'],['s07','10–11']],`
### Das Steckbrief-Gerüst
1. **Herkunft:** Welcher Plexus beziehungsweise welche Wurzeln?
2. **Verlauf:** An welchen Knochenpunkten, Muskeln und Engstellen zieht er vorbei?
3. **Motorik:** Welche Bewegung ermöglicht er über seine Muskeln?
4. **Sensibilität:** Welches Hautgebiet gehört dazu?
5. **Läsion:** Welche Funktionen liegen distal einer möglichen Schädigung?

<div class="flow" role="img" aria-label="Das Steckbrief-Schema in fünf Schritten: Herkunft, Verlauf, Motorik, Sensibilität, Läsion"><div class="flow-step"><strong>1 · Herkunft</strong><small>Plexus/Wurzeln</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>2 · Verlauf</strong><small>Engstellen</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>3 · Motorik</strong><small>Bewegung</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>4 · Sensibilität</strong><small>Hautgebiet</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>5 · Läsion</strong><small>was liegt distal?</small></div></div>
<p class="flow-note">Dieselben fünf Stationen, in derselben Reihenfolge, kommen bei jedem der sechs folgenden Nerven wieder.</p>

### Warum der Ort den Ausfall verändert
Ein Nerv gibt unterwegs Äste ab. Eine distale Läsion betrifft nicht automatisch Muskeln, deren Äste bereits weit proximal abgegangen sind. Deshalb genügt der Nervenname nicht zur Vorhersage aller Ausfälle.

### Symptome sortieren
Kraftverlust, Atrophie und verminderte Sensibilität sind mögliche Ausfälle. Kribbeln ist eine Parästhesie. Schmerzen bei leichter Berührung heißen Allodynie und sind eine veränderte Reizantwort. Vegetative/trophische Veränderungen können Haut, Schweißregulation und Nägel betreffen. Ein Symptom allein beweist keinen bestimmten Engpass.

### Neurodynamik einordnen
ULNT und andere neurodynamische Untersuchungen verändern die mechanische Beanspruchung mehrerer Gewebe. Sie sind keine isolierten Nervenschalter und kein alleiniger Diagnosenachweis. Die Kursabbildungen brauchen praktische Einweisung und Rückmeldung; aus einem Webtext entsteht keine geprüfte Untersuchungskompetenz.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Das fällt dir vielleicht schon auf: Dieses Kapitel macht genau das, was das erste Kapitel in Anatomie 3 auch gemacht hat – es gibt dir kein Fakten-Set, sondern ein **Frage-Set**. Nur sind die Fragen hier enger gefasst, weil sie sich nicht auf jede beliebige Struktur, sondern speziell auf einen benannten peripheren Nerv beziehen: Herkunft, Verlauf, Motorik, Sensibilität, Läsion. Das ist derselbe Trick auf einer spezielleren Ebene: Ein Fach beginnt mit einem wiederverwendbaren Fragenkatalog, nicht mit dem ersten von vielen Einzelfakten. Die restlichen sechs Kapitel dieses Fachs wenden diesen Katalog sechsmal an – du lernst am Ende genau ein Schema, sechsmal befüllt, keine sechs Schemata.`,
'Wenn ein Kabel vor seiner Verzweigung unterbrochen wird, können mehrere Endgeräte ausfallen. Hinter einer Verzweigung betrifft es nur noch einen Teil. Diese räumliche Logik hilft bei der Unterscheidung proximaler und distaler Nervenläsionen.',
[['Grundlage','Welche fünf Fragen gehören zum Steckbrief?','Herkunft, Verlauf, Motorik, Sensibilität und ortsabhängige Läsion.'],['Transfer','Warum sagt „Medianus geschädigt“ allein noch wenig über den Bizeps aus?','Der Bizeps gehört nicht zur Medianusversorgung; zuerst muss die korrekte Muskel-Nerven-Zuordnung geklärt werden.']],'',
'Dieses Kapitel eröffnet PNS mit einem einzigen wiederverwendbaren Steckbrief-Schema (Herkunft, Verlauf, Motorik, Sensibilität, ortsabhängige Läsion). Jedes der sechs folgenden Nervenkapitel wendet genau dieses Schema an – du lernst also nicht sechs verschiedene Vorgehensweisen, sondern eine einzige, sechsmal angewendet.');
const nerves=[
['medianus','N. medianus','s06','2–10','Plexus brachialis, aus lateralem und medialem Faszikel; der Kurs nennt C6–T1.','Medial am Oberarm, durch den Ellenbogenbereich unter der Aponeurose des Bizeps, zwischen Pronator-teres-Anteilen in den Unterarm und unter dem Retinaculum flexorum durch den Karpaltunnel.','Pronator teres/quadratus, Flexor carpi radialis, Palmaris longus, Flexor digitorum superficialis, Flexor pollicis longus, radialer Anteil des tiefen Fingerbeugers; in der Hand unter anderem Opponens und Abductor pollicis brevis sowie Lumbricales I/II.','Vor allem radiale Hohlhand, palmar Finger I–III und radiale Hälfte IV, außerdem distale dorsale Fingeranteile. Die palmare Hautastversorgung muss beim Karpaltunnel differenziert betrachtet werden.','Eine hohe Läsion kann Unterarmfunktionen und Faustschluss betreffen; im Karpaltunnel sind proximal abgehende Muskeläste nicht gleichermaßen betroffen. Die „Schwurhand“ beim Faustschluss gehört nicht pauschal zu jeder Medianusläsion.','Daumenopposition beim Knöpfen einer Jacke.','Warum passt eine Schwäche sämtlicher Unterarmpronatoren nicht zu einem isolierten distalen Karpaltunnelproblem?','Ihre motorischen Äste gehen schon proximal des Karpaltunnels ab.','Das Schema aus dem letzten Kapitel wird hier zum ersten Mal angewendet, an einem der wichtigsten Nerven der Hand. Sein Verlauf durch den Karpaltunnel ist der Bezugspunkt für die beiden nächsten Nerven, die du an anderen Stellen des Arms von ihm unterscheiden lernst.'],
['radialis','N. radialis','s07','2–9','Plexus brachialis, Fasciculus posterior, C5–T1.','Dorsal am Humerus im Sulcus nervi radialis, weiter nach lateral zum Ellenbogen. Aufteilung in oberflächlichen sensiblen und tiefen überwiegend motorischen Ast; der tiefe zieht durch die Supinatorregion.','Trizeps, Hand- und Fingerstrecker, Supinator, Brachioradialis und weitere Muskeln der Streckerregion. Brachioradialis ist eine wichtige Ausnahme: Er beugt den Ellenbogen.','Dorsoradiale Hand sowie je nach Ast Abschnitte von Oberarm/Unterarm. Das Gebiet ist nicht identisch mit einem einzelnen Dermatom.','Bei einer Läsion am Humerusschaft können Hand-/Fingerstreckung ausfallen, während proximal abgegangene Trizepsäste geschont sein können. Eine isolierte tiefe Astläsion erzeugt nicht dasselbe Hautsensibilitätsmuster.','Die Hand beim Loslassen eines Gegenstands öffnen.','Warum muss eine Fallhand nicht mit vollständigem Verlust der Ellenbogenstreckung einhergehen?','Die Trizepsäste können oberhalb der Läsion bereits abgegangen sein.','Der Medianus versorgt vor allem Beuger; der Radialis ist sein Gegenspieler für die Streckerseite des Arms. Dieser Kontrast Beuger/Strecker hilft, beide Nerven auseinanderzuhalten, statt sie einzeln auswendig zu lernen.'],
['ulnaris','N. ulnaris','s08','2–8','Plexus brachialis, Fasciculus medialis, überwiegend C8/T1.','Medial am Arm, hinter dem Epicondylus medialis durch die Ellenbogenregion, zwischen den Köpfen des Flexor carpi ulnaris zum Unterarm und durch die Guyon-Loge in die Hand. Er läuft nicht durch den Karpaltunnel.','Flexor carpi ulnaris, ulnarer Anteil des Flexor digitorum profundus; viele kleine Handmuskeln, darunter Interossei, Lumbricales III/IV, Adductor pollicis und Hypothenar.','Kleinfinger und ulnare Hälfte des Ringfingers; palmar/dorsal abhängig vom jeweiligen Ast.','Ellenbogen und Guyon-Loge sind unterschiedliche mögliche Orte. In der Hand ist der tiefe Ast überwiegend motorisch, der oberflächliche überwiegend sensibel (mit motorischem Anteil zum Palmaris brevis). Nicht beide sind einfach rein motorisch.','Finger spreizen, um eine breite Schüssel zu umfassen.','Verläuft der Ulnaris gemeinsam mit dem Medianus unter dem Retinaculum im Karpaltunnel?','Nein. Er gelangt durch die Guyon-Loge in die Hand.','Medianus und Ulnaris laufen am Unterarm nah beieinander, trennen sich aber am Handgelenk: der eine durch den Karpaltunnel, der andere durch die Guyon-Loge. Genau dieser Kontrast ist der häufigste Verwechslungspunkt zwischen beiden – deshalb steht der Ulnaris direkt nach dem Medianus.'],
['femoralis','N. femoralis','s03','2–8','Plexus lumbalis, üblicherweise L2–L4. Die Folie nennt abweichend L1–L4; das als Rückfrage an den Kurs markieren.','Zwischen Psoas-/Iliacusregion nach kaudal, unter dem Leistenband durch die Lacuna musculorum; der sensible N. saphenus zieht durch den Adduktorenkanal zum medialen Knie und Unterschenkel.','Vor allem Quadrizeps zur Knieextension, außerdem Sartorius und Iliacus; Beteiligungen am Pectineus können variieren. Der Psoas major erhält direkte Plexusäste – „der ganze Iliopsoas nur femoral“ ist zu grob.','Vorderer Oberschenkel über Hautäste, mediale Unterschenkelregion über den N. saphenus.','Eine Schwäche der Knieextension erschwert sichere Lastübernahme. Retroperitoneale Prozesse, Trauma oder Kompression sind mögliche Kontexte im Skript; sie werden nicht aus einer Bewegungsbeobachtung allein diagnostiziert.','Beim Aufstehen aus dem Stuhl das Knie strecken.','Welche Verbindung besteht zum Patellarsehnenreflex?','Der Quadrizeps wird über den Femoralis versorgt und führt die Knieextension aus.','Die ersten drei Nerven kamen alle aus dem Plexus brachialis am Arm. Jetzt wechselt der Ort: Der Femoralis ist der erste Nerv aus dem Plexus lumbalis am Bein. Das Steckbrief-Schema bleibt exakt gleich, nur Plexus und Region wechseln.'],
['fibularis','N. fibularis communis','s04','2–9','Fibularer Anteil des N. ischiadicus aus dem sakralen Plexus; die Folien geben den breiteren Ischiadicus-/Plexusbereich an. Nicht mit einem isolierten Dermatom gleichsetzen.','Über die dorsale Oberschenkel-/Kniekehlenregion zur Fibula. Um den Fibulahals herum; Aufteilung in N. fibularis superficialis und profundus.','Tiefer Ast: Dorsalextension/Fußhebung und Zehenstreckung. Oberflächlicher Ast: vor allem Fibularis longus/brevis zur Eversion. Der kurze Bizeps-femoris-Kopf wird bereits proximal aus dem fibularen Ischiadicusanteil versorgt.','Große Teile des Fußrückens, mit dem ersten Zehenzwischenraum als wichtigem Anker für den tiefen Ast; Randbereiche gehören anderen Nerven.','Am Fibulahals liegt der Nerv oberflächlich. Eine Läsion kann die Fußhebung beeinträchtigen; der proximale kurze Bizepskopf muss dadurch nicht ausfallen.','Beim Gehen die Fußspitze vom Boden lösen.','Warum ist „alle im Steckbrief genannten Muskeln fallen bei Druck am Fibulahals aus“ falsch?','Einige Äste sind schon oberhalb dieser Stelle abgegangen.','Femoralis und die beiden folgenden Beinnerven unterscheiden sich vor allem im Ursprungsplexus: Femoralis kommt aus dem Plexus lumbalis, Fibularis und Tibialis teilen sich dagegen den N. ischiadicus aus dem sakralen Plexus. Der Fibularis übernimmt hier die Streckerseite des Unterschenkels.'],
['tibialis','N. tibialis','s05','2–9','Tibialer Anteil des N. ischiadicus aus dem sakralen Plexus; die Quelle behandelt teilweise den gesamten proximalen Verlauf gemeinsam.','Durch die Kniekehle in die tiefe dorsale Unterschenkelregion, hinter dem Malleolus medialis durch den Tarsaltunnel, Aufteilung zu plantaren Ästen.','Am Unterschenkel unter anderem Triceps surae, Tibialis posterior und lange Zehenbeuger; in der Sohle kleine Fußmuskeln. Die in der Folie zusätzlich genannten hinteren Oberschenkelmuskeln erhalten ihre Äste bereits proximal aus dem tibialen Ischiadicusanteil.','Fußsohle und über beteiligte Äste Fersenregion; die Haut am gesamten dorsalen Unterschenkel lässt sich nicht pauschal einem einzigen distalen Ast zuschreiben.','Eine proximale Läsion kann Plantarflexion beeinträchtigen. Eine distale Einengung im Tarsaltunnel trifft nicht automatisch die bereits proximal versorgte Wadenmuskulatur.','Beim Abstoßen im Gang den Vorfuß belasten.','Warum beweist ein Tarsaltunnelproblem nicht, dass der Triceps surae vollständig gelähmt sein muss?','Die Äste zur Wadenmuskulatur gehen oberhalb des Tarsaltunnels ab.','Fibularis und Tibialis entstehen aus demselben Ischiadicus, teilen sich aber in der Kniekehle in entgegengesetzte Richtungen auf: einer zur Streckerseite, einer zur Beugerseite des Unterschenkels. Mit diesem Kontrast schließt das letzte Kapitel des Fachs PNS die Nervenreihe ab.']
];
for(const [id,title,src,pages,origin,path,motor,sensory,lesion,example,q,a,bridge] of nerves){
 add('pns',id,title,2,`${example} Herkunft, Verlauf und Ausfälle zusammen lernen.`,[[src,pages]],`<div class="flow" role="img" aria-label="Steckbrief-Schema für ${title}: Herkunft, Verlauf, Motorik, Sensibilität, Läsion"><div class="flow-step"><strong>1 · Herkunft</strong></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>2 · Verlauf</strong></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>3 · Motorik</strong></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>4 · Sensibilität</strong></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>5 · Läsion</strong></div></div>\n\n### 1 · Herkunft\n${origin}\n\n### 2 · Verlauf\n${path}\n\n### 3 · Motorische Versorgung\n${motor}\n\n### 4 · Sensibles Gebiet\n${sensory}\n\n### 5 · Ausfälle aus dem Ort ableiten\n${lesion}\n\n### Selbst erklären\nZeichne die Route mit drei Ortsmarken. Nenne dann zwei Bewegungen und ein Hautgebiet ohne Vorlage. Vergleiche proximal und distal. Die neurodynamischen Abbildungen im Original sind Anschauungsmaterial für praktisch angeleitetes Lernen.${id==='tibialis'?'\n\n### Der ganze Weg durch PNS – im Rückblick\nSechs Nerven, ein Schema: Jeder hat dieselben fünf Fragen aus dem ersten Kapitel bekommen – Herkunft, Verlauf, Motorik, Sensibilität, Läsion. Medianus, Radialis und Ulnaris kamen alle aus demselben Plexus brachialis am Arm und ließen sich über den Kontrast Beuger/Strecker sowie Karpaltunnel/Guyon-Loge auseinanderhalten. Femoralis, Fibularis und Tibialis übertragen genau dasselbe Schema auf das Bein – zwei davon aus demselben Ischiadicus, wieder über denselben Kontrast Streckerseite/Beugerseite unterschieden. Am Ende sind das keine sechs auswendig gelernten Nerven, sondern ein Frage-Set, sechsmal an unterschiedlichen Orten angewendet – dasselbe Prinzip, das dir schon im ersten Kapitel von Anatomie 3 begegnet ist.':''}`,example+' Stelle dir die Bewegung vor und beschreibe, welcher Abschnitt bei einer passenden Nervenläsion schwierig werden könnte. Das Beispiel erklärt eine Funktion und ersetzt keine Diagnose.',[['Grundlage','Welche drei räumlichen Stationen merkst du dir für diesen Nerv?',path],['Knifflig',q,a]],id==='ulnaris'?'Materialkorrektur: Die Astaufteilung in den Folien ist widersprüchlich. Oberflächlicher und tiefer Ast sind nicht beide rein motorisch.':'',bridge);
}
