export const subjects = [
 ['anatomie','Anatomie 1','Knochen, Gelenke & Muskeln','Vom Knochenpunkt zur Bewegung. Schultergürtel, Arm und Wirbelsäule.','A1'],
 ['neuroanatomie','Anatomie 3','Nervensystem & Gehirn','Die räumliche Landkarte: Rückenmark, Nervenwurzeln, Hirnregionen und Gefäße.','A3'],
 ['neurophysiologie','Neurophysiologie','Reize, Reflexe & Schmerz','Was mit einer Information auf ihrem Weg durch das Nervensystem passiert.','NP'],
 ['pns','PNS','Die peripheren Nerven','Sechs Nerven verstehen: Verlauf, Versorgung und mögliche Ausfälle.','PN'],
 ['orthopaedie','PT Orthopädie','Knie & Lendenwirbelsäule','Anatomie mit Belastung, Befund und funktionellen Problemen verbinden.','OR'],
 ['mt','Manuelle Therapie','Befund & Gelenkmechanik','Bewegungen unterscheiden und die Logik der Untersuchung verstehen.','MT'],
 ['gyn','PT Gynäkologie','Blase & Schwangerschaft','Lage und Funktion verstehen, Entwicklung und Veränderungen einordnen.','GY'],
 ['paed','PT Pädiatrie','Entwicklung & Neonatologie','Vom Kreislaufwechsel bis zur sensomotorischen Entwicklung.','PÄ']
].map(([id,title,subtitle,description,short])=>({id,title,subtitle,description,short}));
export const lessons=[];
export function add(subject,id,title,level,summary,refs,body,example,questions,notice='',bridge=''){
 lessons.push({subject,id,title,level,summary,refs:refs.map(([id,pages])=>({id,pages})),body,example,questions,notice,bridge});
}
add('neuroanatomie','nervensystem','Die Landkarte des Nervensystems',1,'ZNS/PNS und afferent/efferent sind zwei verschiedene Ordnungssysteme.',[['s00','2–8']],`
### Erst den Ort, dann die Richtung klären
**ZNS** bedeutet zentrales Nervensystem: Gehirn und Rückenmark. **PNS** sind die Nervenstrukturen außerhalb davon. Diese Einteilung beantwortet: Wo befindet sich die Struktur?

**Afferent** heißt: Information läuft zum ZNS. **Efferent** heißt: Information läuft vom ZNS weg zu einem Erfolgsorgan. Diese Einteilung beantwortet: In welche Richtung läuft die Information? Ein peripherer Nerv kann beides enthalten.

<div class="nest" role="img" aria-label="Lageschema: PNS liegt außerhalb, ZNS mit Gehirn und Rückenmark liegt innen"><div class="nest-outer"><div class="nest-label">PNS · außerhalb</div><div class="nest-inner"><strong>ZNS</strong>Gehirn + Rückenmark</div></div></div>
<p class="flow-note">Ort (oben): innen liegt das ZNS, alles außenherum ist PNS – unabhängig davon, wohin die Information gerade läuft.</p>

<div class="flow" role="img" aria-label="Richtungsschema: afferent zum ZNS hin, efferent vom ZNS weg zum Erfolgsorgan"><div class="flow-step"><strong>Rezeptor am Körper</strong><small>z. B. Haut, Muskel</small></div><span class="flow-arrow-labeled" aria-hidden="true"><small>afferent</small><b>→</b></span><div class="flow-step"><strong>ZNS</strong><small>Gehirn / Rückenmark</small></div><span class="flow-arrow-labeled" aria-hidden="true"><small>efferent</small><b>→</b></span><div class="flow-step"><strong>Erfolgsorgan</strong><small>z. B. Muskel</small></div></div>
<p class="flow-note">Richtung (oben): ein und derselbe periphere Nerv kann afferente und efferente Fasern gleichzeitig enthalten – deshalb läuft in der Praxis oft „Hinweg“ und „Rückweg“ nebeneinander im selben Nervenstrang.</p>

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir eine Firma vor: Die Zentrale mit Geschäftsführung ist das ZNS – hier fallen die Entscheidungen. Alle Außenbüros, Vertreter und Kuriere davor sind das PNS. Das ist die Einteilung nach <strong>Ort</strong>. Ganz unabhängig davon liefert jeder Kurier entweder eingehende Post an die Zentrale (afferent, „geht rein“) oder er bringt eine Anweisung aus der Zentrale nach draußen (efferent, „geht raus“). Ein und derselbe Kurier kann an einem Tag beides tun. Deshalb widerspricht „afferent/efferent“ nicht der Einteilung „ZNS/PNS“ – es sind zwei verschiedene Fragen an dieselbe Struktur: Wo ist sie? Und in welche Richtung läuft gerade die Information?</p></div>

### Welche Aufgabe wird geregelt?
Das **somatische Nervensystem** verbindet unter anderem bewusste Wahrnehmung und Skelettmuskulatur. Das **vegetative Nervensystem** reguliert innere Organe. Dazu gehören Sympathikus, Parasympathikus und das enterische Nervensystem. „Somatisch“ bedeutet nicht, dass jede Reaktion bewusst ausgelöst wird: Auch ein Muskelreflex ist somatisch.

<div class="nest" role="img" aria-label="Das vegetative Nervensystem enthält drei gleichrangige Teile: Sympathikus, Parasympathikus und enterisches Nervensystem"><div class="nest-outer"><div class="nest-label">Vegetatives Nervensystem</div><div class="nest-items"><div class="nest-inner"><strong>Sympathikus</strong></div><div class="nest-inner"><strong>Parasympathikus</strong></div><div class="nest-inner"><strong>Enterisches NS</strong></div></div></div></div>

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Somatisch und vegetativ lassen sich gut mit einem Auto vergleichen: Lenkrad, Gaspedal und Bremse steuerst du bewusst – das ist die somatische Seite, die deine Skelettmuskulatur bewegt. Die Klimaanlage, die von selbst nachregelt, oder der Motor, der ohne dein Zutun mit der richtigen Drehzahl läuft, laufen automatisch im Hintergrund – das ist die vegetative Seite an deinen inneren Organen. Der Trick an diesem Kapitel: Ein Kniesehnenreflex sieht aus wie „automatisch“, gehört aber trotzdem zur somatischen Seite, weil er Skelettmuskulatur bewegt, keine inneren Organe reguliert. „Automatisch wirkend“ und „vegetativ“ sind also nicht dasselbe.</p></div>

### Grau und weiß
Graue Substanz enthält besonders viele Nervenzellkörper und Verschaltungen, weiße Substanz besonders viele Nervenfasern. Das ist eine Beschreibung der vorherrschenden Bestandteile, keine vollständige Trennung.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Denk an eine Stadt bei Nacht aus der Vogelperspektive: Die grauen Substanz-Bereiche sind wie Stadtviertel voller Häuser und Büros – dort sitzen die Zellkörper und dort wird „verhandelt“ und verschaltet. Die weiße Substanz ist das Autobahnnetz zwischen den Städten – dort wird nur noch transportiert, nicht mehr verhandelt. Genau wie eine Autobahn auch mal durch eine kleine Ortschaft führt, ist die Trennung nicht absolut – aber als Grundregel gilt: graue Substanz = wo verarbeitet wird, weiße Substanz = wo weitergeleitet wird.</p></div>

### Ein Nerv ist kein einzelner Draht
Endoneurium umgibt einzelne Nervenfasern, Perineurium ein Faszikel, Epineurium den ganzen Nerv. Das Mesoneurium verbindet ihn mit seiner Umgebung und unterstützt seine Beweglichkeit. Blutgefäße versorgen den Nerv; Nervi nervorum versorgen seine Hüllen.

<div class="nest" role="img" aria-label="Nervenhüllen von außen (Mesoneurium) nach innen (Axon) ineinander verschachtelt"><div class="nest-outer"><div class="nest-label">Mesoneurium · lockere Gleithülle</div><div class="nest-inner"><strong>Epineurium</strong><small>ganzer Nerv, mit Fettgewebe und Blutgefäßen</small><div class="nest-inner"><strong>Perineurium</strong><small>um ein Faszikel (Bündel)</small><div class="nest-inner"><strong>Endoneurium</strong><small>um eine einzelne Nervenfaser (Axon)</small></div></div></div></div></div>

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Ein peripherer Nerv ist wie ein dickes Erdkabel mit mehreren Schutzschichten. Ganz innen liegt eine einzelne Ader, umhüllt von einer eigenen dünnen Isolierung – das Endoneurium um eine einzelne Nervenfaser. Mehrere isolierte Adern werden zu einem Bündel zusammengefasst und noch einmal gemeinsam ummantelt – das Perineurium um ein Faszikel. Mehrere solcher Bündel stecken zusammen in einem robusten Außenmantel mit Fettpolster und eigener Blutversorgung – das Epineurium um den ganzen Nerv. Und außen liegt eine lockere, verschiebliche Hülle, das Mesoneurium, damit das ganze Kabel beim Beugen von Arm oder Bein mitgleiten kann, statt sich zu verhaken. Genau diese äußerste Gleitschicht ist der Grund, warum Nerven bei Bewegung überhaupt gleiten müssen – wird das Gleiten gestört, kann ein mechanisches Reizsymptom entstehen, ohne dass die Leitfähigkeit selbst beschädigt ist.</p></div>

### Eine Struktur, fünf Fragen – nicht fünf Themen
Ort, Richtung, Freiwilligkeit, Farbe und Aufbau sind keine fünf getrennten Fakten zum Auswendiglernen. Es sind fünf unabhängige Fragen, die sich ab jetzt an **jede** Struktur in diesem Fach stellen lassen – die Antworten widersprechen sich nie, sie beschreiben nur unterschiedliche Aspekte derselben Sache. Am Beispiel von vorhin, der Berührungsmeldung beim Greifen einer Tasse:

| Frage | Antwort für diese eine Faser |
|---|---|
| Wo? (Ort) | Auf dem Weg von der Hand liegt sie im PNS |
| Welche Richtung? | Afferent – die Meldung läuft zum ZNS |
| Freiwillig oder automatisch? | Somatisch – bewusste Wahrnehmung, Skelettmuskulatur |
| Grau oder weiß? | Im Rückenmark zuerst graue Substanz (Verarbeitung), dann weiße Substanz (Weiterleitung) |
| Wie aufgebaut? | Im Endoneurium, gebündelt im Perineurium, geschützt vom Epineurium, beweglich durch das Mesoneurium |

Dieselbe Faser, fünf gleichzeitig gültige Antworten. Nicht die Antworten selbst sind das Wichtige, sondern die fünf Fragen – die werden in jedem folgenden Kapitel wieder gestellt. Nur das WAS ändert sich (mal ein Rückenmarksegment, mal ein Hirnlappen, mal ein einzelner peripherer Nerv), das WIE-Fragen bleibt dasselbe Werkzeug.`,
'Du greifst eine Tasse. Die Berührungsmeldung aus der Hand läuft afferent zum ZNS. Der Befehl an die Fingerbeuger läuft efferent zurück. Beides kann durch denselben gemischten Nerv laufen. Das Kabelbild hilft beim Bündeln; echte Nerven leiten zusätzlich biologische Signale und brauchen Blutversorgung.',
[['Grundlage','Ist „PNS“ eine Bewegungsrichtung?','Nein. PNS bezeichnet die Lage außerhalb von Gehirn und Rückenmark. Afferent/efferent bezeichnet die Richtung relativ zum ZNS.'],['Transfer','Warum ist „Ein Nerv ist entweder sensibel oder motorisch“ falsch?','Viele periphere Nerven sind gemischt. Verschiedene Fasern übernehmen sensible, motorische und vegetative Aufgaben.']],'',
'Dieses Kapitel eröffnet Anatomie 3 und liefert das Grundgerüst für alle folgenden Kapitel: Ort (ZNS/PNS) und Richtung (afferent/efferent) sind zwei unabhängige Ordnungssysteme, denen du in jedem weiteren Kapitel wieder begegnest.');
add('neuroanatomie','rueckenmark','Rückenmark, Häute & Liquorräume',1,'Den Schutzraum von außen nach innen aufbauen.',[['s10','2–12'],['s19','1–2']],`
### Der Inhalt und seine Hülle
Der **Canalis vertebralis** ist der knöcherne Kanal. Das **Rückenmark** liegt darin. Die Rückenmarkshäute heißen von außen nach innen **Dura mater → Arachnoidea → Pia mater**. Die Pia liegt dem Rückenmark unmittelbar an.

Zwischen Arachnoidea und Pia liegt der **Subarachnoidalraum** mit Liquor. Der epidurale Raum liegt außerhalb der Dura. „Subdural“ bezeichnet einen potenziellen Spaltraum, keinen normalen großen Liquorraum. Spinal- und Epiduralanästhesie nutzen deshalb unterschiedliche Räume; hier geht es um die anatomische Unterscheidung.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Das Rückenmark ist mechanisch fast so schutzlos wie ein rohes Ei – der Körper verpackt es deshalb wie ein zerbrechliches Paket in mehreren Lagen. Der Karton ist der knöcherne Wirbelkanal. Direkt danach kommt eine Luftpolster-Schicht, der Epiduralraum – hier setzt eine Periduralanästhesie an und betäubt gezielt nur ein bis wenige Segmente. Dann folgt eine robuste Lederhülle, die Dura mater, dahinter ein hauchdünner, im Normalfall nicht offener Spalt (Subduralraum) und eine feine Spinnennetz-Schicht, die Arachnoidea. Es folgt ein Wasserkissen, der liquorgefüllte Subarachnoidalraum – hier setzen Lumbalpunktion und Spinalanästhesie an, deshalb wirken sie großflächiger als die PDA im äußeren Luftpolster. Ganz zum Schluss liegt eine hauchdünne Frischhaltefolie direkt auf dem Rückenmark: die Pia mater.</p></div>

<div class="flow" role="img" aria-label="Fließschema der Rückenmarkshüllen von außen (Wirbelkanal) nach innen (Rückenmark)"><div class="flow-step"><strong>Wirbelkanal</strong><small>Knochen</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Epiduralraum</strong><small>Fett · Ort der PDA</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Dura → Arachnoidea</strong><small>Subduralraum dazwischen: schmaler Spalt</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Subarachnoidalraum</strong><small>Liquor · Ort von LP/Spinalanästhesie</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Pia mater</strong><small>liegt direkt auf</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Rückenmark</strong><small>Medulla spinalis</small></div></div>

### Warum unten Nervenwurzeln statt Rückenmark liegen
Beim Erwachsenen endet das Rückenmark meist ungefähr auf Höhe L1/L2 als **Conus medullaris**. Weiter nach unten laufende Wurzeln bilden die **Cauda equina**. Das **Filum terminale** ist dagegen ein fadenförmiger Halteapparat, nicht die Gesamtheit der Nervenwurzeln.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir ein mehrstöckiges Bürohaus vor, dessen Fahrstuhlschacht (das Rückenmark) schon ein paar Stockwerke vor dem Erdgeschoss endet. Die Kabel zu den unteren Stockwerken müssen trotzdem weiter nach unten – sie laufen als loses Kabelbündel im Schacht weiter, das ist die Cauda equina. Ganz in der Mitte dieses Bündels hängt noch ein dünner Halteseil-Strang ohne eigene Leitungsfunktion, der nur die Aufhängung sichert: das Filum terminale. Wer „Filum terminale“ und „Cauda equina“ verwechselt, verwechselt also das Halteseil mit dem eigentlichen Kabelbündel.</p></div>

### Querschnitt lesen
Innen liegt schmetterlingsförmige graue Substanz: Hinterhorn für sensible Verarbeitung, Vorderhorn mit motorischen Nervenzellkörpern, in bestimmten Abschnitten Seitenhorn mit vegetativen Anteilen. Außen verlaufen in weißer Substanz auf- und absteigende Bahnen. In der Mitte liegen Zentralkanal und verbindende Kommissuren.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Schneide dir das Rückenmark gedanklich wie eine Scheibe Wurst quer durch und schau von oben drauf: In der Mitte sitzt ein schmetterlingsförmiger grauer Fleck – das sind die Schaltzentralen. Der hintere Flügel des Schmetterlings (Hinterhorn) nimmt ankommende, sensible Post entgegen. Der vordere Flügel (Vorderhorn) gibt Befehle an die Muskulatur hinaus. Nur in einem mittleren Abschnitt der Wirbelsäule wächst dem Schmetterling noch ein kleiner dritter, seitlicher Flügel (Seitenhorn) für die vegetative Steuerung – das ist kein Merkmal auf ganzer Länge. Rundherum, außen um den Schmetterling, liegt die weiße Substanz: Das sind keine Schaltzentralen mehr, sondern nur noch durchlaufende Kabelstränge auf dem Weg nach oben oder unten.</p></div>

Ein Rückenmarkssegment ist einem Spinalnervenpaar zugeordnet. Ein Wirbelsäulen-Bewegungssegment umfasst dagegen benachbarte Wirbel und ihre Verbindungen. Die Begriffe sind nicht austauschbar.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Die Frage „Wo?“ aus Kapitel 1 war bisher nur eine grobe Zweiteilung (ZNS/PNS). Hier wird sie für einen konkreten Ort des ZNS – das Rückenmark – im Detail beantwortet: Schutzraum, Häute, innerer Aufbau. Die Frage „Grau oder weiß?“ aus Kapitel 1 bekommt hier zum ersten Mal eine räumliche Anordnung mit Hörnern statt nur einer groben Beschreibung. Neu dazu kommt eine Frage, die es in Kapitel 1 noch nicht gab: **Wo genau hört diese Struktur auf?** Das Rückenmark endet nicht einfach irgendwo unten – es hat ein konkretes Ende (Conus medullaris), und was danach kommt (Cauda equina) ist bereits etwas anderes. Genau an diesem Ende setzt das nächste Kapitel an: Dort, wo das Rückenmark aufhört und die Wurzeln beginnen, findet der Übergang von ZNS zu PNS statt, den du in Kapitel 1 bisher nur abstrakt kennengelernt hast.`,
'Stell dir ein mehrstöckiges Haus vor: Das Rückenmark endet vor dem unteren Ende des Gebäudes. Die Leitungen zu tieferen Stockwerken müssen daher noch ein Stück im Kanal nach unten ziehen. Diese Leitungsgruppe ist die Cauda equina.',
[['Grundlage','In welchem Raum befindet sich der Liquor um das Rückenmark?','Im Subarachnoidalraum zwischen Arachnoidea und Pia.'],['Transfer','Sind Filum terminale und Cauda equina dasselbe?','Nein. Das Filum ist ein Haltefaden; die Cauda equina besteht aus Nervenwurzeln.']],
'Materialkorrektur: Das Skript vermischt stellenweise Filum/Cauda equina und Rückenmarks-/Bewegungssegment. Die Begriffe sind hier ausdrücklich getrennt.',
'Im letzten Kapitel hast du ZNS und PNS unterschieden. Das Rückenmark ist der untere Teil des ZNS – hier bekommst du für genau diesen Teil einen konkreten Schutzraum (Kanal, Häute, Liquor) und einen inneren Aufbau (graue/weiße Substanz), auf den die nächsten Kapitel direkt aufbauen.');
add('neuroanatomie','spinalnerv','Von der Wurzel zum gemischten Nerv',2,'Radix und Ramus auseinanderhalten – dann wird die Plexusbildung verständlich.',[['s11','3–11']],`
### Die Reihenfolge ist entscheidend
**Radix dorsalis** führt sensible Afferenzen; im Spinalganglion liegen die zugehörigen Zellkörper. **Radix ventralis** führt motorische beziehungsweise efferente Fasern. Beide vereinigen sich zum kurzen, gemischten Spinalnerv.

Erst danach entstehen **Ramus dorsalis und Ramus ventralis**. Beide sind gemischt. „Dorsale Wurzel ist sensibel“ bedeutet also ausdrücklich nicht „dorsaler Ast ist nur sensibel“.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Denk an zwei getrennte Zulaufrohre, die in einen kurzen gemeinsamen Sammelschacht münden: Ein Rohr bringt nur sensible Fracht (Radix dorsalis, mit einem kleinen Zwischenlager, dem Spinalganglion), das andere nur motorische Fracht (Radix ventralis). Im Sammelschacht – dem eigentlichen Spinalnerv – vermischt sich beides zu einer gemeinsamen Lieferung. Verlässt die Lieferung den Schacht wieder, wird sie erneut in zwei neue Rohre aufgeteilt (Ramus dorsalis/ventralis) – aber diesmal bekommt jedes der beiden neuen Rohre eine gemischte Ladung mit. Deshalb ist „die hintere Wurzel ist sensibel“ wahr, aber „der hintere Ast ist sensibel“ falsch: Wurzel und Ast liegen auf unterschiedlichen Seiten dieses Mischpunkts.</p></div>

<div class="flow" role="img" aria-label="Fließschema: Radix dorsalis und ventralis vereinigen sich zum Spinalnerv, der sich danach wieder in Ramus dorsalis und ventralis aufteilt"><div class="flow-step"><strong>Radix dorsalis</strong><small>sensibel · + Spinalganglion</small></div><div class="flow-step"><strong>Radix ventralis</strong><small>motorisch/efferent</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Spinalnerv</strong><small>kurz, bereits gemischt</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Ramus dorsalis</strong><small>gemischt</small></div><div class="flow-step"><strong>Ramus ventralis</strong><small>gemischt</small></div></div>
<p class="flow-note">Reine Fracht geht rein (getrennte Wurzeln), gemischte Fracht kommt zweimal wieder raus (Spinalnerv und beide Äste).</p>

### Wohin führen die Äste?
Der Ramus dorsalis versorgt unter anderem autochthone Rückenmuskulatur und Haut am Rücken. Die ventralen Äste bilden in Hals-, Arm- und Beinregion Nervengeflechte: Plexus cervicalis, brachialis, lumbalis und sacralis. Im Thorax bleiben viele ventrale Äste als Interkostalnerven segmental organisiert.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Die ventralen Äste verhalten sich wie einzelne Bäche, die sich je nach Landschaft unterschiedlich verhalten. Im Rumpfbereich (Thorax) fließt jeder Bach für sich allein weiter – das sind die klar segmental bleibenden Interkostalnerven. In Hals-, Arm- und Beinregion dagegen fließen mehrere benachbarte Bäche in einem großen Flussdelta zusammen und verzweigen sich danach neu: Das ist der Plexus. Ein einzelner „neuer Flussarm“ nach dem Delta enthält deshalb Wasser aus mehreren ursprünglichen Bächen – genau deshalb gehört zu einem peripheren Nerv nach der Plexusmischung nie nur ein einziges Rückenmarksegment.</p></div>

Der **Ramus meningeus** zieht zurück in den Wirbelkanal und versorgt dort Strukturen. **Rami communicantes** verbinden mit dem sympathischen Grenzstrang. Weiße Verbindungsäste sind typischerweise T1–L2 zugeordnet; graue finden sich auf allen segmentalen Höhen.

### Dermatome sind keine einzelnen peripheren Nerven
Ein Dermatom ist das Hautgebiet einer spinalen Wurzel beziehungsweise eines Segments. Ein peripheres Nervenversorgungsgebiet folgt einem benannten Nerv, der nach der Plexusmischung Fasern mehrerer Segmente enthält. Die Karten können sich überlappen und sind nicht identisch.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Ein Dermatom ist wie eine Postleitzahlen-Karte, gezeichnet direkt an der Quelle: Jedes Rückenmarksegment „besitzt" von Geburt an einen bestimmten Hautstreifen, unabhängig davon, wie das Wasser später verteilt wird. Das periphere Versorgungsgebiet eines benannten Nervs ist dagegen wie die Karte des Trinkwassernetzes nach dem Flussdelta aus dem letzten Abschnitt: Sie folgt den neu gemischten Leitungen, nicht mehr den ursprünglichen Postleitzahlen. Deshalb kann ein und dieselbe Hautstelle auf der Dermatom-Karte anders aussehen als auf der peripheren Nervenkarte – beide sind richtig, sie beantworten nur unterschiedliche Fragen: „Aus welchem Segment stammt die Faser ursprünglich?“ versus „Über welchen benannten Nerv läuft sie jetzt?“.</p></div>

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Hier wird die abstrakte Ort-Grenze aus Kapitel 1 (ZNS/PNS) zum ersten Mal konkret: Die Wurzeln sind der Ort, an dem diese Grenze tatsächlich überschritten wird. Die Richtungs-Frage aus Kapitel 1 (afferent/efferent) bekommt hier ihre anatomische Adresse: Radix dorsalis = afferent, Radix ventralis = efferent. Neu dazu kommt eine Frage, die ab jetzt immer wieder auftaucht, sobald sich Bahnen mischen oder aufteilen: **Ist das, was hier herauskommt, noch dasselbe wie das, was hineingegangen ist?** Nach der Vereinigung zum Spinalnerv und der Neuaufteilung in Plexus lautet die Antwort „nein“ – eine Faser trägt ihre ursprüngliche Segmentherkunft zwar weiter in sich, reist aber in einem neu gemischten Bündel. Genau dieses Werkzeug – Herkunft und aktuellen Verlauf getrennt betrachten – brauchst du später im Fach PNS bei jedem einzelnen peripheren Nerv wieder.`,
'Wie Straßen vor und nach einem Verkehrsknoten: Die Wurzeln kommen getrennt an. Nach der Vereinigung und Neuverteilung verlaufen im selben Ast unterschiedliche „Verkehrsarten“. So kann ein Hautgebiet Hinweise auf eine Wurzel oder einen peripheren Nerv geben – je nach Muster.',
[['Grundlage','Welche beiden Strukturen vereinigen sich zum Spinalnerv?','Dorsale und ventrale Wurzel.'],['Knifflig','Warum kann eine Schädigung des Ramus dorsalis Muskeln schwächen?','Der Ramus dorsalis ist gemischt und enthält auch motorische Fasern zur autochthonen Rückenmuskulatur.']],
'Materialkorrektur: Wurzeln und Äste sowie Dermatome und periphere Hautgebiete werden in den Folien teilweise zu stark gleichgesetzt. Auch die Angabe zu allen Rami communicantes ist zu pauschal.',
'Im Rückenmark-Kapitel hast du im Querschnitt Vorderhorn (motorisch) und Hinterhorn (sensibel) gesehen. Genau an diesen beiden Hörnern entstehen die ventrale und dorsale Wurzel – das ist der Übergang von ZNS zu PNS, den du hier lernst, bevor sich daraus Plexus und periphere Nerven bilden.');
add('neuroanatomie','hirnlappen','Großhirnlappen: Aufgaben räumlich ordnen',2,'Nicht nur Namen lernen: Jede Region mit einer Funktion verbinden.',[['s12','3–9']],`
### Vier Lappen, vier Orientierungspunkte
**Frontal:** willkürliche Motorik, Planung und Handlungssteuerung. Der präzentrale Gyrus enthält primär-motorische Areale. Sprachproduktion ist bei den meisten Menschen überwiegend links organisiert.

**Parietal:** somatosensorische Verarbeitung, Körper- und Raumorientierung. Der postzentrale Gyrus verarbeitet unter anderem Informationen aus Haut und Bewegungsapparat.

**Okzipital:** visuelle Verarbeitung. Sehinformation erreicht die Sehrinde über vorgeschaltete Stationen; der Sehnerv endet nicht einfach direkt dort.

**Temporal:** Hörverarbeitung sowie wichtige Anteile von Sprachverständnis und Gedächtnis. Das limbische System verbindet unter anderem Gedächtnis, Emotion und Motivation; es ist kein einzelner fünfter Hirnlappen.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir das Großhirn wie ein Gebäude mit vier Abteilungen von vorne nach hinten vor. Vorne sitzt die Planungsabteilung (Frontallappen): Hier wird entschieden, geplant und die Bewegung losgeschickt – bei den meisten Menschen liegt hier links auch die Sprachproduktion, sozusagen die Redakteursabteilung. Direkt dahinter sitzt die Poststelle (Parietallappen), die eingehende Körpermeldungen von Haut und Bewegungsapparat sortiert und Raum/Körper zueinander in Beziehung setzt. Ganz hinten liegt ein fensterloser Kinosaal (Okzipitallappen), der ausschließlich Bilder verarbeitet – die Leitung dorthin läuft über mehrere Zwischenstationen, nicht als direkter Draht vom Auge. Seitlich, auf Ohrhöhe, liegt das Archiv mit Tonanlage (Temporallappen): Hören, Sprachverständnis und ein großer Teil des Gedächtnisses. Das limbische System ist in diesem Bild keine eigene Abteilung, sondern eher die Hausverwaltung, die Emotion, Motivation und Gedächtnis quer durch mehrere Abteilungen mitsteuert.</p></div>

### Tiefer verstehen
Funktionen entstehen in Netzwerken. Ein Zuordnungssatz wie „Frontal = Bewegung“ ist ein Einstieg, keine vollständige Funktionskarte. Für eine Prüfungsantwort nennst du Region, eine Kernaufgabe und ein denkbares Ausfallbeispiel.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Wie Kapitel 2 fürs Rückenmark, beantwortet dieses Kapitel die Ort-Frage aus Kapitel 1 jetzt für die zweite ZNS-Hälfte: das Gehirn. Neu ist hier eine Verknüpfung, die vorher nicht nötig war: **Ort → Funktion.** Ein Hirnlappen ist nicht nur ein Platz auf einer Landkarte, sondern ein Platz mit einer Aufgabe. Genau diese Ort-Funktion-Kopplung ist das Werkzeug, das das letzte Kapitel dieses Fachs braucht: Erst wenn du weißt, welche Aufgabe ein Lappen hat, ergibt es einen Sinn, warum der Ausfall eines bestimmten Blutgefäßes ausgerechnet diese eine Fähigkeit kostet und keine andere.`,
'Du siehst einen Schlüssel, erkennst ihn, planst das Greifen und spürst ihn in der Hand. Sehen, Erkennen, Planen, Bewegen und Fühlen brauchen zusammenarbeitende Regionen. Ein einziger „Schlüsselbereich“ würde das nicht erklären.',
[['Grundlage','Welche Lappen verbindest du zuerst mit Sehen und Körperempfindung?','Okzipital mit Sehen, Parietal mit somatosensorischer Verarbeitung.'],['Transfer','Warum reicht eine Hirnlappenliste nicht zur genauen Diagnose?','Weil Funktionen verteilt sind und Ausfälle von genauer Lage, Ausmaß und Netzwerkverbindungen abhängen.']],'',
'Die letzten beiden Kapitel haben den unteren Teil des ZNS aufgebaut: Rückenmark und die daraus austretenden Wurzeln. Jetzt wandert der Blick nach oben, zum zweiten großen ZNS-Bestandteil aus dem allerersten Kapitel: dem Gehirn. Die Einteilung in Lappen ist die räumliche Landkarte, die das nächste Kapitel über Gefäße braucht.');
add('neuroanatomie','hirngefaesse','Hirngefäße & Versorgungsgebiete',3,'Vom Zufluss zu ACA, MCA und PCA – ohne gefährliche Sicherheits-Abkürzungen.',[['s12','10–20']],`
### Zwei Zuflüsse
Die **Aa. carotides internae** bilden den vorderen Zufluss. Die **Aa. vertebrales** ziehen aus der Subclavia kommend durch die Halsregion und vereinigen sich zur **A. basilaris**. Der Circulus arteriosus verbindet vordere und hintere Stromgebiete über kommunizierende Arterien.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Denk an die Wasserversorgung einer Stadt aus zwei unabhängigen Wasserwerken: Ein Wasserwerk vorne (die beiden Aa. carotides internae) und ein zweites, das aus zwei kleineren Werken zu einem gemeinsamen Hauptrohr zusammengeführt wird (die beiden Aa. vertebrales münden in die eine A. basilaris). Damit bei Ausfall eines Werks nicht sofort ein ganzer Stadtteil trocken fällt, sind vorderes und hinteres Rohrnetz zusätzlich über einen Ringschluss verbunden – das ist der Circulus arteriosus. Ein Ringschluss ist aber kein Garant: Er kann einen Ausfall abfedern, aber nicht bei jeder Person gleich gut und nicht immer vollständig.</p></div>

<div class="flow" role="img" aria-label="Fließschema der Hirndurchblutung von den Zuflüssen bis zum Circulus arteriosus"><div class="flow-step"><strong>Aa. carotides internae</strong><small>vorderer Zufluss</small></div><div class="flow-step"><strong>Aa. vertebrales</strong><small>aus der Subclavia</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>A. basilaris</strong><small>Vereinigung beider Vertebrales</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Circulus arteriosus</strong><small>Ringschluss vorne/hinten</small></div></div>
<p class="flow-note">Von dort verzweigt sich die Versorgung in drei große Endstromgebiete:</p>
<div class="flow" role="img" aria-label="Die drei großen Hirnarterien mit ihren Versorgungsgebieten"><div class="flow-step"><strong>ACA</strong><small>mediale Flächen · Bein</small></div><div class="flow-step"><strong>MCA</strong><small>laterale Flächen · Arm/Gesicht · Sprache</small></div><div class="flow-step"><strong>PCA</strong><small>Okzipital · Hirnstamm/Kleinhirn</small></div></div>

### Drei große Namen
**ACA (A. cerebri anterior):** vor allem mediale Großhirnflächen; im motorischen/sensiblen Kontext ist die Beinrepräsentation ein wichtiger Anker.

**MCA (A. cerebri media):** große laterale Flächen und tiefe Äste; unter anderem Arm/Gesicht sowie auf der dominanten Seite wichtige Sprachnetzwerke.

**PCA (A. cerebri posterior):** unter anderem Okzipitalregion und visuelle Verarbeitung. Vertebrobasiläre Äste versorgen außerdem Hirnstamm und Kleinhirn.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Jetzt lässt sich die Gebäudekarte aus dem letzten Kapitel wie ein Gartengrundstück mit drei Sprenger-Kreisen betrachten: Ein Sprenger vorne-mittig (ACA) bewässert vor allem den schmalen Innenstreifen des Grundstücks – dort liegt zufällig die Beinvertretung der Planungsabteilung. Ein großer, breiter Sprenger seitlich (MCA) deckt den größten Rasenteil ab – Arm- und Gesichtsvertretung sowie, auf der dominanten Seite, die Redakteursabteilung für Sprache. Ein dritter Sprenger ganz hinten (PCA) bewässert ausschließlich den fensterlosen Kinosaal von vorhin, den Okzipitallappen, und läuft nebenbei über dieselbe Leitung wie Hirnstamm und Kleinhirn. Fällt ein Sprenger aus, vertrocknet also nicht „ein Hirnlappen“, sondern genau der Rasenbereich, den dieser eine Sprenger bedient – deshalb passt ein Ausfallmuster zum Gefäßgebiet, nicht zur Lappengrenze.</p></div>

### Nicht auswendig übervereinfachen
Kollateralen können einen Ausfall teilweise ausgleichen, garantieren das aber nicht. Ein Gefäßverschluss hat keine immer identische Symptomkombination. Die in den Folien gezeigten provokativen Halspositionstests sind keine zuverlässige Freigabe für eine Behandlung. Das IFOMPT-Rahmenwerk verwendet eine umfassende klinische Einschätzung statt eines einzelnen negativen Positionstests.

### Der ganze Weg durch Anatomie 3 – im Rückblick
Fünf Kapitel, ein Faden: Kapitel 1 gab dir fünf Fragen als Werkzeug – Wo? Welche Richtung? Freiwillig oder automatisch? Grau oder weiß? Wie aufgebaut? Kapitel 2 und 3 haben damit die untere ZNS-Hälfte vollständig durchgearbeitet: erst der Ort selbst (Rückenmark, Häute, innerer Aufbau), dann genau die Stelle, an der die Ort-Grenze aus Kapitel 1 real überschritten wird (Wurzel → Spinalnerv → Ast → Plexus). Kapitel 4 hat dieselbe Ort-Frage für die obere ZNS-Hälfte gestellt, das Gehirn, und ihr eine neue Kopplung hinzugefügt: Ort bedeutet auch Funktion. Dieses letzte Kapitel schließt den Kreis, indem es zeigt, dass jede Funktion aus Kapitel 4 nur so lange arbeitet, wie ihr Gefäßgebiet durchblutet ist. Struktur, Funktion und Versorgung sind am Ende dieselbe Landkarte, nur aus drei verschiedenen Blickwinkeln betrachtet.`,
'Wenn auf einer Stadtkarte die Brücke einer Hauptstraße ausfällt, hängt die Versorgung von Ort und Nebenwegen ab. Genau deshalb lernst du Gefäß und typisches Gebiet zusammen, ohne aus dem Namen eine sichere Einzeldiagnose abzuleiten.',
[['Grundlage','Welche Arterien vereinigen sich zur Basilaris?','Die beiden Aa. vertebrales.'],['Knifflig','Ein Positionstest ist negativ. Ist damit eine Gefäßproblematik ausgeschlossen?','Nein. Ein negativer provokativer Positionstest ist keine verlässliche Sicherheitsfreigabe.']],
'Fachlicher Abgleich: IFOMPT Cervical Framework 2020/2023, https://www.ifompt.org/site/ifompt/IFOMPT%20cervical%20framework%20final%202020%20Add%202023.pdf . Die Sicherheitsfolgerung aus den Unterrichtsfolien wird hier nicht übernommen.',
'Du kennst jetzt die vier Hirnlappen und ihre Aufgaben. Damit diese Regionen überhaupt arbeiten können, brauchen sie Blutversorgung. Dieses letzte Kapitel schließt den Kreis: welches Gefäß welchen Lappen versorgt – und warum ein Ausfallmuster nie nur „ein Lappen“, sondern immer auch „ein Gefäßgebiet“ bedeutet.');
add('neurophysiologie','reflex','Reflexbogen, Eigen- & Fremdreflex',1,'Fünf Stationen erklären, statt eine Definition herunterzusagen.',[['s09','2–8'],['s09','14–16']],`
### Vom Reiz zur Antwort
**Rezeptor → afferente Faser → zentrale Verschaltung → efferente Faser → Effektor.** Ein Reflex ist eine unwillkürliche Antwort. Das Gehirn kann Reflexe beeinflussen; die schnelle spinale Verschaltung benötigt aber keine vorherige bewusste Entscheidung.

<div class="flow" role="img" aria-label="Fließschema des Reflexbogens von Rezeptor bis Effektor"><div class="flow-step"><strong>Rezeptor</strong><small>nimmt Reiz auf</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Afferente Faser</strong><small>zum Rückenmark</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Zentrale Verschaltung</strong><small>im Rückenmark</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Efferente Faser</strong><small>zum Muskel</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Effektor</strong><small>z. B. Muskel</small></div></div>
<p class="flow-note">Diese fünf Stationen sind das Grundmuster für beide folgenden Reflexarten – sie unterscheiden sich nur darin, wie die mittlere Station (die Verschaltung) aufgebaut ist.</p>

### Eigenreflex
Reizaufnahme und Antwort finden im selben Organ statt. Beim Muskeldehnungsreflex registriert die **Muskelspindel** eine Dehnung; die Ia-Afferenz aktiviert das passende α-Motoneuron. Die direkte erregende Verbindung ist monosynaptisch. Die zusätzliche Hemmung des Gegenspielers benötigt ein Interneuron.

<div class="flow" role="img" aria-label="Fließschema des Eigenreflexes am Beispiel der Muskelspindel, monosynaptisch"><div class="flow-step"><strong>Muskelspindel</strong><small>registriert Dehnung</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Ia-Afferenz</strong><small>direkt, eine Synapse</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>α-Motoneuron</strong><small>desselben Muskels</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Kontraktion</strong><small>Agonist</small></div></div>
<p class="flow-note">Nur diese eine Verbindung ist monosynaptisch. Die gleichzeitige Hemmung des Gegenspielers läuft über ein zusätzliches Interneuron auf einem eigenen, polysynaptischen Nebenweg – „der Eigenreflex ist monosynaptisch" gilt also nur für die erregende Hauptstrecke, nicht für die gesamte Schaltung.</p>

### Fremdreflex
Rezeptor und Effektor liegen in unterschiedlichen Organen, etwa Hautreiz und Muskelantwort. Die Verschaltung ist polysynaptisch. Beim Rückziehreflex beugt sich die gereizte Extremität; beim gekreuzten Streckreflex kann die Gegenseite die Stützfunktion übernehmen.

<div class="flow" role="img" aria-label="Fließschema des Fremdreflexes: ein Hautreiz löst zwei gegensätzliche Antworten auf beiden Körperseiten aus"><div class="flow-step"><strong>Hautreiz</strong><small>z. B. spitzer Gegenstand am Fuß</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Polysynaptische Verschaltung</strong><small>im Rückenmark</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Ipsilateral: Flexion</strong><small>Rückzug der gereizten Seite</small></div><div class="flow-step"><strong>Kontralateral: Extension</strong><small>Stützfunktion der Gegenseite</small></div></div>

### Häufige Verwechslung
Das Golgi-Sehnenorgan erfasst Spannung und gehört mit Ib-Afferenzen zu anderen Regelkreisen. Es ersetzt nicht die Muskelspindel im klassischen Dehnungsreflex.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Muskelspindel und Golgi-Sehnenorgan sind zwei unterschiedliche Sensoren an zwei unterschiedlichen Orten, die leicht verwechselt werden, weil beide im Muskel-Sehnen-Bereich sitzen. Die Muskelspindel liegt im Muskelbauch selbst und ist wie ein Dehnungsmesser: Sie meldet, wie sehr und wie schnell sich der Muskel in die Länge zieht – das ist die Grundlage des klassischen Dehnungsreflexes. Das Golgi-Sehnenorgan sitzt dagegen in der Sehne, am Übergang zum Knochen, und funktioniert eher wie ein Kraftmesser: Es meldet die Zugspannung, unabhängig davon, ob diese Spannung durch Dehnung oder durch aktive Kontraktion entsteht. Ein Dehnungsmesser und ein Kraftmesser beantworten unterschiedliche Fragen – deshalb gehören sie zu unterschiedlichen Regelkreisen mit unterschiedlichen Afferenzen (Ia für die Spindel, Ib für das Sehnenorgan).</p></div>

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Der Reflexbogen ist keine neue Grunderfindung – er ist eine Anwendung von zwei Werkzeugen, die du schon aus Anatomie 3 kennst: die Richtung afferent/efferent aus Kapitel 1 dort, und die graue Substanz als Ort der Verschaltung aus dem Rückenmarkskapitel. Neu ist hier die Frage, wie viele Verschaltungen dazwischenliegen: **monosynaptisch** (eine Synapse, wie beim Eigenreflex) oder **polysynaptisch** (mehrere, wie beim Fremdreflex mit seiner gekreuzten Antwort). Diese Frage – wie viele Zwischenstationen liegen zwischen Reiz und Antwort? – begegnet dir in jedem der folgenden Kapitel wieder, sobald ein Signal verarbeitet statt nur weitergeleitet wird.`,
'Du trittst überraschend auf etwas Spitzes. Das betroffene Bein zieht sich zurück. Das andere Bein muss gleichzeitig Last übernehmen, damit du nicht umfällst. Das erklärt den Sinn der gekreuzten Reaktion.',
[['Grundlage','Was ist der Rezeptor beim klassischen Muskeldehnungsreflex?','Die Muskelspindel.'],['Knifflig','Ist beim monosynaptischen Eigenreflex jede beteiligte Verschaltung monosynaptisch?','Nein. Die direkte erregende Ia-α-Verbindung ist monosynaptisch; zusätzliche Schaltungen wie die reziproke Hemmung nicht.']],
'Korrektur gegenüber der vermischten Darstellung in den Folien. Abgleich: Purves, Neuroscience, „The Stretch Reflex“, https://www.ncbi.nlm.nih.gov/books/NBK10809/ .',
'Dieses Kapitel eröffnet Neurophysiologie mit dem einfachsten vollständigen Schaltkreis: dem Reflexbogen (Rezeptor → afferent → Verschaltung → efferent → Effektor). Diese fünf Stationen und die Unterscheidung Eigen-/Fremdreflex sind das Grundmuster, das in jedem folgenden Kapitel wiederkehrt, sobald ein Reiz verarbeitet wird.');
add('neurophysiologie','kennreflexe','Kennmuskeln & klinische Reflexe',1,'Segment, Bewegung und Reflex gemeinsam abrufen.',[['s09','9–13'],['s09','17']],`
### Vier sichere Anker aus deinem Skript
| Reflex | Muskel/Antwort | Segmentanker im Kurs |
|---|---|---|
| Bizepssehnenreflex | Bizeps, Ellenbogenflexion | C5/C6 |
| Trizepssehnenreflex | Trizeps, Ellenbogenextension | C7 |
| Patellarsehnenreflex | Quadrizeps, Knieextension | L3/L4 |
| Achillessehnenreflex | Triceps surae, Plantarflexion | S1/S2 |

### Kennmuskel bedeutet Schwerpunkt
Ein Kennmuskel hilft bei der segmentalen Orientierung. Er wird meistens aus mehreren Wurzeln versorgt. Deshalb ist „ein Muskel = genau eine Wurzel“ zu grob. Deine Tabelle nennt unter anderem Deltoideus, Bizeps, Trizeps, Handmuskeln, Quadrizeps, Tibialis anterior und Triceps surae.

Gehe bei jeder Zeile so vor: **Segment → Muskel → Bewegung → passender peripherer Nerv**. Vergleiche anschließend, ob sensible und reflektorische Befunde zum gleichen Muster passen. Ein schwacher Muskel allein lokalisiert eine Läsion nicht sicher.

<div class="flow" role="img" aria-label="Klinischer Denkweg von einem geprüften Segment über den Muskel und die Bewegung zum passenden peripheren Nerv"><div class="flow-step"><strong>Segment</strong><small>z. B. L3/L4</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Muskel</strong><small>z. B. Quadrizeps</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Bewegung</strong><small>z. B. Knieextension</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Peripherer Nerv</strong><small>z. B. N. femoralis</small></div></div>
<p class="flow-note">Diese vier Stationen laufen bei jeder Zeile der Tabelle gleich ab – nur Segment, Muskel, Bewegung und Nerv tauschen sich aus.</p>

### Faserklassen einordnen
Die Tabelle unterscheidet A-, B- und C-Fasern. Große myelinisierte Fasern leiten schneller als kleine unmyelinisierte. Ia-/Aα-Fasern sind für schnelle propriozeptive Regelung wichtig; Aδ- und C-Fasern begegnen dir bei der Nozizeption.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Stell dir das Nervensystem als Straßennetz vor: Die dicken, stark isolierten Aα-Fasern sind breite, gut ausgebaute Autobahnen – hier rast die Information für schnelle propriozeptive Regelung mit hoher Geschwindigkeit. Aδ-Fasern sind schon schmalere Landstraßen, dünner und weniger stark isoliert. C-Fasern sind unbefestigte Feldwege ohne jede Isolierung – die Information „zuckelt" hier deutlich langsamer. Genau dieser Geschwindigkeitsunterschied erklärt, warum ein kurzer, heller Schmerz (schnellere Aδ-Landstraße) meist vor einem dumpfen Nachschmerz (langsamerer C-Feldweg) ankommt. Faserdicke und Myelinisierung sind dabei zwei Zutaten für dasselbe Ergebnis: mehr von beidem bedeutet mehr Tempo.</p></div>

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
„Segment" ist kein neuer Begriff – er stammt aus dem Rückenmarkskapitel in Anatomie 3, wo er eine anatomische Einheit war. Hier wird er zum klinischen Werkzeug: **Segment → Muskel → Bewegung → peripherer Nerv** ist eine Kette, die du bei jedem Reflex neu durchgehst, egal welches Segment gerade geprüft wird. Neu dazu kommen die Faserklassen A/B/C nach Leitungsgeschwindigkeit – dieses Werkzeug brauchst du unverändert in den nächsten beiden Kapiteln wieder, sobald es um afferente Bahnen geht.`,
'Beim Treppensteigen muss das Knie stabil strecken. Ordne die Funktion dem Quadrizeps zu, dann dem N. femoralis und schließlich den Segmentankern. So wird die Reflexliste zu einer Funktionskarte.',
[['Grundlage','Welcher Reflex passt zur Plantarflexion?','Der Achillessehnenreflex mit dem Triceps surae.'],['Transfer','Warum beweist ein schwacher Quadrizeps allein keine bestimmte Wurzelläsion?','Mehrere Wurzeln, der periphere Nerv, Muskel und weitere Faktoren können beteiligt sein; zusätzliche Befunde sind nötig.']],'',
'Im letzten Kapitel hast du den Reflexbogen an der Muskelspindel kennengelernt. Jetzt bekommen die dort beteiligten Ia-Afferenzen ein klinisches Gesicht: feste Reflexe mit Segmentanker, an denen sich im Rahmen einer Untersuchung ein Rückenmarksegment prüfen lässt. Die hier eingeführten Faserklassen A/B/C brauchst du in den nächsten beiden Kapiteln wieder.');
add('neurophysiologie','beruehrung','Mechanorezeptoren: Was wird wahrgenommen?',2,'Druck, Bewegung, Dehnung und Vibration getrennt betrachten.',[['s01','2–7']],`
### Vom mechanischen Reiz zum Signal
Verformung der Haut beeinflusst spezialisierte Rezeptoren. Daraus entsteht ein elektrisches Signal in der afferenten Bahn. Ein Rezeptor kann bestimmte Reize besonders gut abbilden; das bedeutet nicht, dass er ein kleines fertiges Bild des Gegenstands sendet.

<div class="flow" role="img" aria-label="Fließschema vom mechanischen Reiz an der Haut zum afferenten Signal"><div class="flow-step"><strong>Hautverformung</strong><small>Druck, Dehnung, Vibration</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Mechanorezeptor</strong><small>z. B. Merkel, Pacini</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Elektrisches Signal</strong><small>in der afferenten Bahn</small></div></div>

| Rezeptor | Nützlicher Lernanker | Anpassung |
|---|---|---|
| Merkel | anhaltender Druck, Formdetails | langsam |
| Meissner | bewegte leichte Berührung | schnell |
| Ruffini | Hautdehnung | langsam |
| Pacini | rasche Veränderungen, Vibration | sehr schnell |

### Was heißt Adaptation?
Bei einem gleichbleibenden Reiz nimmt die Aktivität schnell adaptierender Rezeptoren stark ab. Sie melden besonders Veränderungen. Langsam adaptierende Rezeptoren liefern länger Information über einen anhaltenden Zustand. **Schnell adaptierend** und **schnelle Nervenleitung** sind zwei verschiedene Eigenschaften.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Schnell adaptierende Rezeptoren funktionieren wie eine Türklingel: Sie melden laut den Moment, in dem sich etwas verändert – der Finger drückt den Knopf – und verstummen dann wieder, obwohl der Finger noch auf dem Knopf liegt. Langsam adaptierende Rezeptoren sind eher wie ein Thermostat: Sie melden fortlaufend, wie der aktuelle Zustand gerade ist, solange dieser Zustand anhält. Wichtig ist, diese Eigenschaft nicht mit der Leitungsgeschwindigkeit zu verwechseln: Ein Rezeptor kann schnell adaptieren (schnell verstummen) und trotzdem über eine unterschiedlich schnelle Faser melden – „schnell reagierend" und „schnell leitend" sind zwei verschiedene Zifferblätter derselben Uhr.</p></div>

Rezeptive Felder sind die Bereiche, aus denen eine Faser Information erhält. Kleine Felder und dichte Versorgung unterstützen eine feine räumliche Unterscheidung.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Hier beginnt eine neue Teilkette innerhalb von Neurophysiologie: Die letzten beiden Kapitel haben die efferente, motorische Seite betont – jetzt beginnt die afferente Seite ganz am Anfang, beim Rezeptor selbst. Neu ist die Trennung zwischen dem, WAS ein Rezeptor meldet (Reizqualität, Adaptationsverhalten), und WIE SCHNELL diese Meldung weiterläuft (die Faserklasse aus dem letzten Kapitel) – zwei unabhängige Eigenschaften derselben Faser, kein Widerspruch. Genau diese Trennung – Rezeptor liefert das Was, die Bahn bestimmt das Wohin und Wie-schnell – ist das Werkzeug, das die nächsten beiden Kapitel direkt weiterführen.`,
'Beim Anziehen spürst du den Ärmel deutlich. Später fällt die gleichbleibende Berührung weniger auf. Bewegt sich der Stoff plötzlich, bemerkst du die Veränderung erneut. Dieses Beispiel erklärt Adaptation, ohne alle beteiligten Rezeptoren auf einen Typ zu reduzieren.',
[['Grundlage','Welcher Rezeptor ist ein Anker für Vibration?','Pacini-Körperchen.'],['Knifflig','Bedeutet schnelle Adaptation automatisch schnelle Leitung?','Nein. Adaptation beschreibt die Antwort auf einen anhaltenden Reiz; Leitung die Ausbreitung entlang der Faser.']],'',
'Die Reflexkapitel haben die efferente, motorische Seite eines Signals betont. Jetzt wechselt der Blick auf die afferente Seite: Welche Rezeptoren erzeugen überhaupt das Signal, das in einem Reflexbogen ankommt oder bewusst wahrgenommen wird? Ohne diese Rezeptortypen ergibt das nächste Kapitel über aufsteigende Bahnen keinen Sinn.');
add('neurophysiologie','sensible-bahnen','Sensible Bahnen: Wo kreuzt die Information?',2,'Feine Berührung und Schmerz anhand ihrer Kreuzung unterscheiden.',[['s01','8–14'],['s02','15–17']],`
### Feine Berührung und bewusste Propriozeption
Die Hinterstrangbahn steigt zunächst **auf derselben Seite im Rückenmark** auf. Untere Körperabschnitte verlaufen im Fasciculus gracilis, obere zusätzlich im Fasciculus cuneatus. Umschaltung und Kreuzung erfolgen in der **Medulla oblongata**. Danach führt der Weg über den Lemniscus medialis zum Thalamus und zur somatosensorischen Großhirnrinde.

<div class="flow" role="img" aria-label="Fließschema der Hinterstrangbahn: lange ipsilaterale Strecke, Kreuzung erst in der Medulla oblongata"><div class="flow-step"><strong>Rezeptor</strong><small>Berührung/Propriozeption</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Hinterstrang</strong><small>ipsilateral aufsteigend</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Kreuzung</strong><small>erst in der Medulla oblongata</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Lemniscus medialis</strong><small>jetzt kontralateral</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Thalamus → Kortex</strong><small>somatosensorisch</small></div></div>

### Schmerz und Temperatur
Die Afferenz wird im Hinterhorn verschaltet. Die weiterführenden Fasern kreuzen schon auf Rückenmarksebene und ziehen im anterolateralen System, unter anderem im Tractus spinothalamicus, nach oben. Schmerzverarbeitung umfasst zusätzliche verteilte Systeme.

<div class="flow" role="img" aria-label="Fließschema der Schmerz-/Temperaturbahn: kurze ipsilaterale Strecke, frühe Kreuzung schon im Rückenmark"><div class="flow-step"><strong>Rezeptor</strong><small>Schmerz/Temperatur</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Hinterhorn</strong><small>Umschaltung</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Kreuzung</strong><small>schon auf Rückenmarksebene</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Tractus spinothalamicus</strong><small>jetzt kontralateral</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Thalamus</strong><small>+ verteilte Systeme</small></div></div>
<p class="flow-note">Der einzige, aber klinisch entscheidende Unterschied zur Hinterstrangbahn oben: Hier liegt die Kreuzung direkt am Anfang, nicht erst am Ende der Strecke.</p>

### Warum die Kreuzung wichtig ist
Bei einer Schädigung im Rückenmark sind feine Berührung/Propriozeption und Schmerz/Temperatur nicht zwangsläufig auf derselben Körperseite betroffen. Für die Begründung musst du wissen, ob die betreffende Bahn ihre Kreuzung schon passiert hat. Grobe Berührung wird in den Kursfolien ebenfalls spinothalamischen Anteilen zugeordnet; setze sie nicht mit der gesamten Mechanosensibilität gleich.

### Was dieses Kapitel zum Werkzeugkasten hinzufügt
Die Rezeptoren aus dem letzten Kapitel bekommen hier ihren Weg. Neu ist die **Kreuzungsfrage**: Auf welcher Höhe wechselt eine Bahn die Körperseite – früh im Rückenmark oder erst oben in der Medulla? Diese eine Frage erklärt, warum eine Rückenmarksschädigung Berührung und Schmerz unterschiedlich auf beiden Körperseiten betreffen kann. Das letzte Kapitel dieses Fachs nimmt genau eine dieser beiden Bahnen – die Schmerzbahn – und verfolgt sie bis zu ihrem Ziel weiter.`,
'Zeichne zwei Aufzüge links und rechts. Die feine Berührung fährt erst bis zur Medulla hoch und wechselt dort. Die Schmerzbahn wechselt früh im Rückenmark. Markiere nun eine Unterbrechung: Welche Information kommt dort auf welcher Seite vorbei?',
[['Grundlage','Wo kreuzt die Hinterstrang-Lemniscus-medialis-Bahn?','In der Medulla oblongata nach Umschaltung in den Hinterstrangkernen.'],['Knifflig','Warum ist „Alle sensiblen Bahnen kreuzen sofort im Rückenmark“ falsch?','Die Hinterstrangbahn steigt zunächst ipsilateral auf; die Kreuzung erfolgt erst in der Medulla.']],
'Die Folien vereinfachen die Wege stellenweise. Abgleich der Hinterstrangbahn: https://www.ncbi.nlm.nih.gov/books/NBK11142/ .',
'Du kennst jetzt die Rezeptoren, die ein Signal erzeugen. Dieses Kapitel verfolgt das Signal weiter: Auf welchem Weg im Rückenmark steigt es auf, und wo kreuzt es zur Gegenseite? Diese Kreuzungsfrage ist die Grundlage für das letzte Kapitel, in dem es um eine bestimmte Bahn – die Schmerzbahn – im Detail geht.');
add('neurophysiologie','schmerz','Nozizeption ist nicht gleich Schmerz',3,'Gewebereiz, Weiterleitung und persönliche Erfahrung auseinanderhalten.',[['s02','5–14'],['s02','18–21']],`
### Zwei Begriffe
**Nozizeption** bezeichnet die neuronale Verarbeitung potenziell schädigender Reize. **Schmerz** ist eine unangenehme persönliche sensorische und emotionale Erfahrung. Die Erfahrung wird von biologischen, psychologischen und sozialen Faktoren beeinflusst. Das bedeutet nicht, dass sie eingebildet ist.

<div class="flow" role="img" aria-label="Fließschema von der Gewebereizung über die Nozizeption bis zum persönlichen Schmerzerleben, moduliert durch Kontext"><div class="flow-step"><strong>Gewebereiz</strong><small>potenziell schädigend</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Nozizeption</strong><small>neuronale Verarbeitung</small></div><span class="flow-arrow" aria-hidden="true">→</span><div class="flow-step"><strong>Schmerz</strong><small>persönliches Erleben</small></div></div>
<p class="flow-note">Zwischen den letzten beiden Stationen liegt kein direkter Draht: Kontext, Erwartung und Aufmerksamkeit greifen genau an dieser Stelle ein, bevor aus Nozizeption tatsächlich Schmerzerleben wird.</p>

### Von der Peripherie zum Erleben
Aδ- und C-Fasern leiten nozizeptive Information. Entzündungsmediatoren können die Reizantwort verändern: Ein zuvor wenig empfindlicher Bereich reagiert dann stärker. Auf dem weiteren Weg können Signale verstärkt oder gehemmt werden. Aufmerksamkeit, Bedrohung, Erfahrung und Kontext beeinflussen das Erleben.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Entzündungsmediatoren wirken auf Nozizeptoren wie ein hochgedrehter Lautstärkeregler auf ein Mikrofon: Dieselbe leise Berührung, die vorher kaum ein Signal erzeugt hätte, wird jetzt als deutlich lauter – also schmerzhafter – wahrgenommen, weil der Regler in der entzündeten Region weiter aufgedreht ist. Das Mikrofon selbst hat sich nicht verändert, nur seine Empfindlichkeit. Genauso können Aufmerksamkeit und Erwartung an anderer Stelle in der Kette einen zusätzlichen Regler bedienen – mal lauter, mal leiser – ohne dass sich am ursprünglichen Gewebereiz etwas ändert.</p></div>

### Begriffe sauber verwenden
**Hypalgesie:** verminderte Schmerzempfindlichkeit. **Analgesie:** fehlende Schmerzempfindung. **Hyperalgesie:** verstärkter Schmerz bei normalerweise schmerzhaftem Reiz. **Allodynie:** Schmerz bei einem normalerweise nicht schmerzhaften Reiz. **Parästhesie:** ungewöhnliche Empfindung wie Kribbeln. **Anästhesie** ist weiter gefasst als Analgesie und betrifft Empfindungsverlust.

<div class="box analogie"><div class="box-label">Einfach erklärt</div><p>Diese Begriffe lassen sich auf einer einzigen Reglerskala für „Schmerzempfindlichkeit" anordnen. Ganz unten, bei null Empfindung überhaupt, steht die Anästhesie. Etwas darüber, aber noch unterhalb von normal, liegt die Hypalgesie – gedämpfte, aber noch vorhandene Schmerzempfindung. Bei „null Schmerzempfindung speziell" liegt die Analgesie, die enger gefasst ist als Anästhesie, weil sie nur den Schmerzanteil betrifft, nicht jede Empfindung. Oberhalb von normal, bei überschießender Reaktion auf einen ohnehin schmerzhaften Reiz, liegt die Hyperalgesie. Ganz oben, wo sogar ein eigentlich harmloser Reiz plötzlich schmerzhaft wird, liegt die Allodynie – der Regler ist dort so weit aufgedreht, dass er auf einer Stufe reagiert, die eigentlich noch gar keinen Schmerz auslösen sollte. Parästhesie steht neben dieser Skala: Sie beschreibt keine Lautstärke, sondern eine andersartige Empfindungsqualität wie Kribbeln.</p></div>

### Medikamentenfolien einordnen
Die Unterlagen erwähnen NSAR und Opioide. Als Grundidee: NSAR beeinflussen die Prostaglandinbildung; Opioide wirken an Opioidrezeptoren. Das ersetzt weder eine ärztliche Auswahl noch Dosierungswissen. Das INOMT-Ebenenmodell in der Quelle ist ein Unterrichtsmodell; insbesondere seine energetischen Annahmen sind nicht mit gesicherter Neurophysiologie gleichzusetzen.

### Der ganze Weg durch Neurophysiologie – im Rückblick
Fünf Kapitel, ein Faden: Das erste Kapitel hat gezeigt, dass ein Reflex nichts anderes ist als afferent/efferent aus Anatomie 3, kombiniert mit einer Verschaltung in der grauen Substanz – nur jetzt als funktionierender Schaltkreis statt als reine Anatomie. Kapitel 2 hat diesen Schaltkreis an feste Segmente gebunden und damit klinisch nutzbar gemacht. Kapitel 3 und 4 haben die afferente Seite dieses Schaltkreises im Detail aufgeschlüsselt: erst der Rezeptor (was wird gemeldet?), dann die Bahn (wohin, und wo kreuzt sie?). Dieses letzte Kapitel nimmt eine einzige dieser Bahnen – die Schmerzbahn – und verfolgt sie bis an ihr Ende, wo aus reiner Reizverarbeitung (Nozizeption) erst durch Kontext und Erwartung ein persönliches Erleben (Schmerz) wird. Reflexbogen, Segment, Rezeptor, Bahn und Erleben sind am Ende keine fünf Themen, sondern fünf Stationen auf demselben Signalweg, den du in Anatomie 3 zuerst nur als abstraktes Gerüst kennengelernt hast.`,
'Eine leichte Berührung am Sonnenbrand tut weh, obwohl dieselbe Berührung an unverletzter Haut angenehm wäre. Das ist ein verständlicher Anker für Allodynie und Sensibilisierung. Es beweist allein keine bestimmte Ursache bei einer realen Person.',
[['Grundlage','Wie heißt Schmerz durch normalerweise nicht schmerzhaften Reiz?','Allodynie.'],['Transfer','Kann man aus der Schmerzstärke direkt die Größe eines Gewebeschadens berechnen?','Nein. Schmerz und Gewebeschaden stehen nicht in einer einfachen Eins-zu-eins-Beziehung.']],
'Die wiederholte Begriffstabelle in mehreren Nerven-PDFs setzt Anästhesie und Analgesie fälschlich gleich. Allodynie ist außerdem kein reines Ausfallsymptom.',
'Das letzte Kapitel hat gezeigt, dass Schmerzsignale im anterolateralen System früh kreuzen und über den Tractus spinothalamicus aufsteigen. Jetzt geht es um das, was am Ende dieser Bahn ankommt: der Unterschied zwischen reiner Reizverarbeitung (Nozizeption) und persönlichem Erleben (Schmerz) – der Abschluss von Neurophysiologie.');
